# Generated by Django 2.2.4 on 2019-08-30 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('numero', models.IntegerField(default='', primary_key=True, serialize=False, verbose_name='Número')),
            ],
            options={
                'verbose_name': 'Apartamento',
                'verbose_name_plural': 'Apartamentos',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Conjunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Nit')),
                ('razon_social', models.CharField(max_length=100, verbose_name='Razón Social')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('telefono', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('nombre_administrador', models.CharField(max_length=50, verbose_name='Nombre Administrador')),
                ('numero_unidades', models.IntegerField(blank=True, default=0, null=True, verbose_name='Número Unidades')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='static/')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('pagina_web', models.URLField(blank=True, default='', null=True, verbose_name='Link Página Web')),
            ],
        ),
        migrations.CreateModel(
            name='Interior',
            fields=[
                ('numero', models.IntegerField(default='', primary_key=True, serialize=False, verbose_name='Número')),
            ],
            options={
                'verbose_name': 'Interior',
                'verbose_name_plural': 'Interiores',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Parqueadero',
            fields=[
                ('numero', models.IntegerField(default='', primary_key=True, serialize=False, verbose_name='Número')),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Apartamento')),
                ('interior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Interior')),
            ],
            options={
                'verbose_name': 'Parqueadero',
                'verbose_name_plural': 'Parqueaderos',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='TipoIngreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'TipoIngreso',
                'verbose_name_plural': 'TipoIngresos',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Vigilante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Vigilante',
                'verbose_name_plural': 'Vigilantes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('identificacion', models.CharField(default='', max_length=20, primary_key=True, serialize=False, verbose_name='Identificaciòn')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('foto', models.ImageField(blank=True, default='/static/img/no-avatar.jpg', null=True, upload_to='static/')),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitante',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('placa', models.CharField(default='', max_length=10, primary_key=True, serialize=False, verbose_name='placa')),
                ('tipo_vehiculo', models.CharField(choices=[('automovil', 'Automóvil'), ('camioneta', 'Camioneta')], max_length=15, verbose_name='Tipo de vehículo')),
                ('uso', models.CharField(choices=[('particular', 'Particular'), ('publico', 'Público')], max_length=15, verbose_name='Tipo de Uso')),
                ('marca', models.CharField(default='', max_length=20, verbose_name='Marca')),
                ('modelo', models.IntegerField(blank=True, default=0, null=True, verbose_name='Modelo')),
                ('color', models.CharField(default='', max_length=30, verbose_name='Color')),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Apartamento')),
                ('interior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Interior')),
                ('parqueadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Parqueadero')),
            ],
            options={
                'verbose_name': 'vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('identificacion', models.CharField(default='', max_length=20, primary_key=True, serialize=False, verbose_name='Identificaciòn')),
                ('nombre', models.CharField(default='', max_length=50, verbose_name='Nombre')),
                ('tipo_residente', models.CharField(choices=[('propietario', 'Propietario'), ('arrendatario', 'Arrendatario')], max_length=20, verbose_name='Propietario/Residente')),
                ('telefono', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Teléfono')),
                ('celular', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Celular')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('edad', models.IntegerField(blank=True, default=0, null=True, verbose_name='Edad')),
                ('persona_discapacitada', models.CharField(choices=[('no', 'No'), ('si', 'Si')], max_length=5, verbose_name='Persona con Discapacidad')),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Apartamento')),
                ('interior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Interior')),
            ],
            options={
                'verbose_name': 'Residente',
                'verbose_name_plural': 'Residentes',
                'ordering': ['identificacion'],
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('identificacion', models.CharField(default='', max_length=20, primary_key=True, serialize=False, verbose_name='Identificaciòn')),
                ('nombre', models.CharField(default='', max_length=50, verbose_name='Nombre')),
                ('telefono', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Teléfono')),
                ('celular', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Celular')),
                ('direccion', models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='Dirección')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Apartamento')),
                ('interior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Interior')),
            ],
            options={
                'verbose_name': 'Propietario',
                'verbose_name_plural': 'Propietarios',
                'ordering': ['identificacion'],
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=20, verbose_name='Nombre')),
                ('tipo_mascota', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('otro', 'Otro')], max_length=10, verbose_name='Tipo de Mascota')),
                ('raza', models.CharField(default='', max_length=20, verbose_name='Raza')),
                ('edad', models.IntegerField(blank=True, default=0, null=True, verbose_name='Edad')),
                ('vacuna', models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=5, verbose_name='Vacuna')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='conjuntos', verbose_name='Foto Mascota')),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Apartamento')),
                ('interior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Interior')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Inmobiliaria',
            fields=[
                ('código', models.IntegerField(default='', primary_key=True, serialize=False, verbose_name='Código')),
                ('nit', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Nit')),
                ('razon_social', models.CharField(max_length=100, verbose_name='Razón Social')),
                ('nombre_contacto', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Nombre Contacto')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('pagina_web', models.URLField(blank=True, default='', null=True, verbose_name='Link Página Web')),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Apartamento')),
                ('interior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Interior')),
            ],
            options={
                'verbose_name': 'Inmobiliaria',
                'verbose_name_plural': 'Inmobiliarias',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='Ingreso_vehiculo',
            fields=[
                ('placa', models.CharField(default='', max_length=10, primary_key=True, serialize=False, verbose_name='placa')),
                ('tipo_ingreso', models.CharField(choices=[('visitante', 'Visitante'), ('residente', 'Residente')], max_length=15, verbose_name='Visitante/Residente')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='static/')),
                ('hora_ingreso', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('hora_salida', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Apartamento')),
                ('interior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Interior')),
                ('vigilante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Vigilante')),
            ],
            options={
                'verbose_name': 'Ingreso Vehículo',
                'verbose_name_plural': 'Ingreso Vehículos',
                'ordering': ['hora_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='Ingreso_peatonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='static/')),
                ('hora_ingreso', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('hora_salida', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Hora de Salida')),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Apartamento', verbose_name='Apartamento')),
                ('identificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Visitante', verbose_name='Identificaciòn')),
                ('interior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Interior', verbose_name='Interior')),
                ('tipoingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TipoIngreso', verbose_name='Tipo de Ingreso')),
                ('vigilante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vigilante')),
            ],
            options={
                'verbose_name': 'Ingreso Peatonal',
                'verbose_name_plural': 'Ingresos Peatonales',
                'ordering': ['hora_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('numero', models.IntegerField(default='', primary_key=True, serialize=False, verbose_name='Número')),
                ('valor_arriendo', models.FloatField(default=0, verbose_name='Valor Arriendo')),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Apartamento')),
                ('interior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Interior')),
            ],
            options={
                'verbose_name': 'Depósito',
                'verbose_name_plural': 'Depósitos',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Correspondencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remitente', models.CharField(default='', max_length=100, verbose_name='Remitente')),
                ('destinatario', models.CharField(default='', max_length=100, verbose_name='Destinatario')),
                ('clase_correspondencia', models.CharField(choices=[('sobre', 'Sobre'), ('paquete', 'Paquete')], default='', max_length=10, verbose_name='Clase de Correspondencia')),
                ('tipo_correspondencia', models.CharField(choices=[('normal', 'Normal'), ('urgente', 'Urgente')], default='', max_length=10, verbose_name='Tipo de Correspondencia')),
                ('detalle', models.CharField(default='', max_length=300, null=True, verbose_name='Detalle')),
                ('fecha_recibo', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('fechahora_notifica', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('entregado', models.BooleanField(blank=True, default=False, null=True)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Apartamento')),
                ('interior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Interior')),
                ('vigilante', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vigilante')),
            ],
            options={
                'verbose_name': 'Correspondencia',
                'verbose_name_plural': 'Correspondencias',
                'ordering': ['fecha_recibo'],
            },
        ),
        migrations.CreateModel(
            name='Autorizado',
            fields=[
                ('identificacion', models.CharField(default='', max_length=20, primary_key=True, serialize=False, verbose_name='Identificaciòn')),
                ('nombre', models.CharField(default='', max_length=50, verbose_name='Nombre')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='static/')),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Apartamento')),
                ('interior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Interior')),
                ('tipoingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TipoIngreso')),
            ],
            options={
                'verbose_name': 'Autorizado',
                'verbose_name_plural': 'Autorizados',
                'ordering': ['identificacion'],
            },
        ),
    ]
