# Generated by Django 3.2.5 on 2021-07-09 16:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20210709_1136'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingreso_peatonal',
            new_name='IngresoPeatonal',
        ),
        migrations.RenameModel(
            old_name='Ingreso_vehiculo',
            new_name='IngresoVehiculo',
        ),
    ]
