# Generated by Django 3.2.5 on 2021-07-17 00:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210716_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correspondencia',
            options={'ordering': ['fechahora_recibo'], 'verbose_name': 'Correspondencia', 'verbose_name_plural': 'Correspondencias'},
        ),
        migrations.RemoveField(
            model_name='correspondencia',
            name='fecha_recibo',
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='fechahora_recibo',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha Hora Recibo'),
        ),
        migrations.AlterField(
            model_name='correspondencia',
            name='fechahora_notifica',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha Hora Notifica'),
        ),
    ]
