# Generated by Django 3.2.5 on 2021-07-19 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_auto_20210716_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaComun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, default='/static/img/no-avatar.jpg', null=True, upload_to='static/')),
                ('descripcion', models.CharField(max_length=80, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Zona Común',
                'verbose_name_plural': 'Zonas Comunes',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='ReservaZonasComunes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechahora_inicial', models.DateTimeField()),
                ('fechahora_final', models.DateTimeField()),
                ('anexo', models.ImageField(blank=True, default='/static/img/no-avatar.jpg', null=True, upload_to='static/')),
                ('pagado', models.BooleanField(blank=True, default=False, null=True)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.apartamento', verbose_name='Apartamento')),
                ('interior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.interior', verbose_name='Interior')),
                ('residente', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Residente')),
                ('zona_comun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.zonacomun', verbose_name='zona_comun')),
            ],
            options={
                'verbose_name': 'Ingreso Peatonal',
                'verbose_name_plural': 'Ingresos Peatonales',
                'ordering': ['fechahora_inicial'],
            },
        ),
    ]
