# Generated by Django 3.2.5 on 2021-07-20 00:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_reservazonascomunes_zonacomun'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservazonascomunes',
            options={'ordering': ['fechahora_inicial'], 'verbose_name': 'Reserva Zona Común', 'verbose_name_plural': 'Reserva Zonas Comunes'},
        ),
        migrations.AddField(
            model_name='reservazonascomunes',
            name='horas',
            field=models.IntegerField(default=0, verbose_name='Horas'),
        ),
        migrations.AddField(
            model_name='reservazonascomunes',
            name='minutos',
            field=models.IntegerField(default=0, verbose_name='Minutos'),
        ),
        migrations.AlterField(
            model_name='reservazonascomunes',
            name='fechahora_final',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha Hora Final'),
        ),
        migrations.AlterField(
            model_name='reservazonascomunes',
            name='fechahora_inicial',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha Hora Inicial'),
        ),
        migrations.AlterField(
            model_name='zonacomun',
            name='foto',
            field=models.ImageField(blank=True, default='/static/img/placeholderpng.png', null=True, upload_to='static/'),
        ),
    ]
