# Generated by Django 3.2.5 on 2021-07-23 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210722_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservazonascomunes',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha'),
        ),
    ]
