# Generated by Django 3.2.5 on 2021-07-24 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210723_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservazonascomunes',
            name='anio',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(2021), django.core.validators.MaxValueValidator(2031)], verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='reservazonascomunes',
            name='dia',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Día'),
        ),
        migrations.AddField(
            model_name='reservazonascomunes',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default=0, verbose_name='Mes'),
        ),
    ]
