# Generated by Django 3.2.5 on 2021-07-24 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210724_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservazonascomunes',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='reservazonascomunes',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='reservazonascomunes',
            name='mes',
        ),
        migrations.AddField(
            model_name='reservazonascomunes',
            name='fecha_inicial',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='Fecha Inicial'),
        ),
    ]
