# Generated by Django 3.2.5 on 2021-07-25 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210724_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservazonascomunes',
            options={'ordering': ['fecha_inicial'], 'verbose_name': 'Reserva Zona Común', 'verbose_name_plural': 'Reserva Zonas Comunes'},
        ),
        migrations.AlterField(
            model_name='reservazonascomunes',
            name='fecha_inicial',
            field=models.TimeField(default=datetime.datetime.today, verbose_name='Fecha Inicial'),
        ),
    ]
