# Generated by Django 3.2.5 on 2021-07-25 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210725_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservazonascomunes',
            name='fecha_inicial',
            field=models.DateField(default=datetime.datetime(2021, 7, 25, 13, 37, 33, 318746), verbose_name='Fecha Inicial'),
        ),
    ]
