# Generated by Django 3.2.5 on 2021-07-25 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_reservazonascomunes_fecha_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservazonascomunes',
            name='fecha_inicial',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Fecha Inicial'),
        ),
    ]
