# Generated by Django 3.2.5 on 2021-07-27 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_reservazonascomunes_fecha_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservazonascomunes',
            name='hora_incial',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Horas'),
        ),
    ]
