# Generated by Django 3.2.5 on 2021-07-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210727_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservazonascomunes',
            name='horario',
            field=models.CharField(choices=[('Am', 'Am'), ('Pm', 'Pm')], default='', max_length=2, verbose_name='Horario'),
        ),
    ]
