# Generated by Django 3.2.5 on 2021-08-04 22:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_reservazonascomunes_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonacomun',
            name='observaciones',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='reservazonascomunes',
            name='hora_inicial',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Hora Inicial'),
        ),
        migrations.AlterField(
            model_name='reservazonascomunes',
            name='horario',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='', max_length=2, verbose_name='Horario'),
        ),
        migrations.AlterField(
            model_name='reservazonascomunes',
            name='horas',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Horas'),
        ),
    ]
