# Generated by Django 3.2.5 on 2021-08-04 22:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210804_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonacomun',
            name='observaciones',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Observaciones'),
        ),
    ]
