# Generated by Django 3.2.5 on 2021-08-09 23:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_zonacomun_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservazonascomunes',
            name='hora_final',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Hora Final'),
        ),
    ]
