# Generated by Django 3.2.5 on 2021-08-23 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0025_filtros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_apartamento', to='core.apartamento', verbose_name='Apartamento')),
                ('interior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_interior', to='core.interior', verbose_name='Interior')),
                ('residente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
