# Generated by Django 3.2.5 on 2021-08-27 17:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['interior', 'apartamento'], 'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AddField(
            model_name='residente',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residente',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'otro'), ('', 'No Determinado')], default='', max_length=15, null=True, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='residente',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de edicion'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='celular',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Celular'),
        ),
        migrations.CreateModel(
            name='residente_otros',
            fields=[
                ('identificacion', models.CharField(default='', max_length=20, primary_key=True, serialize=False, verbose_name='Identificaciòn')),
                ('nombre', models.CharField(default='', max_length=50, verbose_name='Nombre')),
                ('celular', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Celular')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('edad', models.IntegerField(blank=True, default=0, null=True, verbose_name='Edad')),
                ('persona_discapacitada', models.CharField(choices=[('No', 'No'), ('Si', 'Si'), ('', 'No Determinado')], max_length=5, verbose_name='Persona con Discapacidad')),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'otro'), ('N', 'No Determinado')], default='', max_length=15, null=True, verbose_name='Género')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.apartamento')),
                ('interior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.interior')),
            ],
            options={
                'verbose_name': 'Otro Residente',
                'verbose_name_plural': 'Otros Residentes',
                'ordering': ['identificacion'],
            },
        ),
    ]
