# Generated by Django 3.2.5 on 2021-08-30 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20210827_1237'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='residente_otros',
            new_name='ResidenteOtros',
        ),
    ]
