# Generated by Django 3.2.5 on 2021-08-30 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_rename_residente_otros_residenteotros'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResidenteOtros',
            new_name='ResidenteOtro',
        ),
    ]
