# Generated by Django 3.2.5 on 2021-08-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_residenteotro_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartamento',
            name='id',
            field=models.AutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autorizado',
            name='id',
            field=models.AutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deposito',
            name='id',
            field=models.AutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingresovehiculo',
            name='id',
            field=models.AutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inmobiliaria',
            name='id',
            field=models.AutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interior',
            name='id',
            field=models.AutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parqueadero',
            name='id',
            field=models.AutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propietario',
            name='id',
            field=models.AutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residente',
            name='id',
            field=models.AutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residenteotro',
            name='id',
            field=models.AutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='id',
            field=models.AutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitante',
            name='id',
            field=models.AutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartamento',
            name='numero',
            field=models.IntegerField(default='', verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='autorizado',
            name='identificacion',
            field=models.CharField(default='', max_length=20, verbose_name='Identificaciòn'),
        ),
        migrations.AlterField(
            model_name='deposito',
            name='numero',
            field=models.IntegerField(default='', verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='ingresovehiculo',
            name='placa',
            field=models.CharField(default='', max_length=10, verbose_name='placa'),
        ),
        migrations.AlterField(
            model_name='inmobiliaria',
            name='código',
            field=models.IntegerField(default='', verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='interior',
            name='numero',
            field=models.IntegerField(default='', verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='parqueadero',
            name='numero',
            field=models.IntegerField(default='', verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='identificacion',
            field=models.CharField(default='', max_length=20, verbose_name='Identificaciòn'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='identificacion',
            field=models.CharField(default='', max_length=20, verbose_name='Identificaciòn'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='tipo_residente',
            field=models.CharField(choices=[('Propietario', 'Propietario'), ('Arrendatario', 'Arrendatario'), ('Residente', 'Residente'), ('', 'No Determinado')], max_length=15, verbose_name='Propietario/Residente'),
        ),
        migrations.AlterField(
            model_name='residenteotro',
            name='identificacion',
            field=models.CharField(default='', max_length=20, verbose_name='Identificaciòn'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(default='', max_length=10, verbose_name='placa'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='identificacion',
            field=models.CharField(default='', max_length=20, verbose_name='Identificaciòn'),
        ),
    ]
