"""
Django settings for conjuntos project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '#0fmzfks_5s)4wtuj&!srm#=3rso8a64p-rw*qkfs)dpke=k%g'
SECRET_KEY = 'gh5m&7m%h)mhxe%t5so+1umy9$z0(x3a3-2c#g-rpcygt(3fl_'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #'conjuntos.apps.ConjuntosConfig'
    #'conjuntos',
    'core',
    'upload',
    'pages.apps.PagesConfig',
    'social.apps.SocialConfig',
    'registration',
    'profiles',
    
    #'services.apps.ServicesConfig',
    #'crispy_forms',
    #'bootstrap4',
    #'bootstrapform',
    #'material',
    #material.frontend',#
    #'material.admin',#
    #'blog',
    #'materializecssform',
    #'thumbnail',
    #'viewflow',#
    #'viewflow.frontend' ,
    
    #'materializecssform',
    'bootstrap_datepicker_plus',
    'bootstrap_modal_forms',
    'bootstrap4',
    'crispy_forms',
    'django_tables2',
    'django_filters',
    'import_export',
    'ckeditor',
    #'ckeditor_uploader',
    'django.contrib.humanize',
    #'datetimepicker',
    #'import_export',
    #'reportlab',
    'bootstrap3_datetime',
    'pwa',
           
      
]

""" MESSAGE_STORAGE = 'django.contrib.messages.storage.cookie.CookieStorage' """
MESSAGE_STORAGE = 'django.contrib.messages.storage.fallback.FallbackStorage'
CKEDITOR_JQUERY_URL = 'https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js'

CKEDITOR_UPLOAD_PATH = 'uploads/'
#CKEDITOR_IMAGE_BACKEND = "pillow"


CKEDITOR_CONFIGS = {
    'default': {
        'height': 'full',
        'width': 'full',
    },
}


""" CKEDITOR_UPLOAD_PATH = '/static/'  """

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'responsive.middleware.ResponsiveMiddleware',
    #'pagination.middleware.PaginationMiddleware', 
]

from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: "alert-secondary",
    messages.INFO: "alert-info",
    messages.SUCCESS: "alert-success",
    messages.WARNING: "alert-warning",
    messages.ERROR: "alert-danger",
}

""" DATETIME_INPUT_FORMATS = ["%Y-%m-%dT%H:%M:%S", "%Y-%m-%dT%H:%M"] """

DJANGO_TABLES2_PAGE_RANGE = 15

ROOT_URLCONF = 'conjuntos.urls'

BOOTSTRAP4 = {
    'include_jquery': True,
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                #'core.processors.ctx_dict',
                'social.processors.ctx_dict',
                
            ],
        },
    },
]


WSGI_APPLICATION = 'conjuntos.wsgi.application'



# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases


DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'conjuntosDB',
            'USER': 'Joaquin',
            'PASSWORD': 'Jjg0712@BX',
            'HOST': 'localhost',
            'PORT': '3306',
        }
    }

""" DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR,'db.conjuntos'),
    }
} """

""" DATABASES = {

    'default': {

        'ENGINE': 'django.db.backends.postgresql_psycopg2',

        'NAME': ‘<db_name>’,

        'USER': '<db_username>',

        'PASSWORD': '<password>',

        'HOST': '<db_hostname_or_ip>',

        'PORT': '<db_port>',

    }

} """

DJANGO_TABLES2_TEMPLATE = "django_tables2/bootstrap.html"

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/


""" DATE_INPUT_FORMATS = [
    '%d.%m.%Y', '%d.%m.%y',  # European
    '%Y-%m-%d',  # ISO (for native mobile datepickers)
    '%m/%d/%Y', '%m/%d/%y',  # US
    '%d %b %Y', '%d %B %Y',  # some long formats
] """




DATE_FORMAT = 'j F Y'
TIME_FORMAT = 'H:i'
DATETIME_FORMAT = 'j F Y H:i'
YEAR_MONTH_FORMAT = 'F Y'
MONTH_DAY_FORMAT = 'j F'
SHORT_DATE_FORMAT = 'j N Y'
SHORT_DATETIME_FORMAT = 'j N Y H:i'
FIRST_DAY_OF_WEEK = 1

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_L10N = False

USE_TZ = True

LANGUAGE_CODE = 'es-Es'

TIME_ZONE = 'America/Bogota'

#DATETIME_FORMAT = 'd/m/Y'
DATE_INPUT_FORMATS = (
    '%d/%m/%Y',  # '21/03/2014'
)
SHORT_DATE_FORMAT = 'd/m/Y'
DECIMAL_SEPARATOR = u'.'
THOUSAND_SEPARATOR = u','
USE_THOUSAND_SEPARATOR = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_URL = '/media/'


from django.conf.locale.en import formats as en_formats
en_formats.DATE_FORMAT = "d M Y"

#Lugar a donde se suben los archivos
MEDIA_ROOT = os.path.join(BASE_DIR,'media')
STATIC_ROOT = os.path.join(BASE_DIR,'static')
#print(STATIC_ROOT)
#print(os.path)


SETTINGS_PATH = os.path.normpath(os.path.dirname(__file__))

CRISPY_TEMPLATE_PACK = 'bootstrap4'

JQUERY_URL=False

USE_DJANGO_JQUERY = True

TEMPLATE_CONTEXT_PROCESSORS = ( 
    'django.social.context_processors.media', 
    'django.social.context_processors.static',
    'django.core.context_processors.request',
        
)

AUTH_AUTHENTICATION_TYPE = 'both'

#AUTHENTICATION_BACKENDS = (
#'accounts.backends.EmailOrUsernameModelBackend',
#)

DAB_FIELD_RENDERER = 'django_admin_bootstrapped.renderers.BootstrapFieldRenderer'

LOGIN_REDIRECT_URL = '/main'
LOGOUT_REDIRECT_URL = '/main'

#MESSAGE_TAGS = {
#    mensajes.EXITO: ​​'alerta-éxito exitoso',
#    mensajes.ADVERTENCIA: 'alerta de advertencia de alerta',
#    messages.ERROR: 'error de alerta-peligro'
#}

#messages.success (solicitud, "Mi mensaje de éxito")
#messages.warning (solicitud, "Mi mensaje de advertencia")
#messages.error (solicitud, "Mi mensaje de error")


# Email config
EMAIL_HOST = 'smtp.mailtrap.io'
EMAIL_HOST_USER = 'c68fc0356c8df7'
EMAIL_HOST_PASSWORD = 'b72bc41b1b23e1'
EMAIL_PORT = '2525'

LOGIN_URL = '/user_home/0'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

PWA_APP_NAME = "conjuntos"
PWA_APP_DESCRIPTION = "administración de conjuntos residenciales" #app description
PWA_APP_THEME_COLOR = "#34787f5" # theme color
PWA_APP_BACKGROUND_COLOR = "#6699f7"

PWA_APP_ICONS = [{"src": "/static/core/img/condominium.png", "sizes": "640x640"}] # app icon
PWA_APP_ICONS_APPLE = [{"src": "/static/core/img/condominium.png", "sizes": "160x160"}]