from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include
from core import views as view

from registration.urls import registration_patterns
from upload.urls import upload_patterns
from  django.views  import  generic 
from core import views
from django.contrib.auth import views as auth_views
#from pwa.views import manifest, service_worker, offline

urlpatterns = [
    
    path('', include("pwa.urls")),   

    path('admin/', admin.site.urls),
    path('',view.BaseHomePageView.as_view(), name="home_page"),
    path('home/',view.BaseHomePageView.as_view(), name="home"),
    path('',view.UserHomeView,name='user_home'),
    path('user_home/<int:tipo_usuario>/',view.UserHomeView,name='user_home'),
    #path("pwa", include("pwa.urls")),
    path('main/',view.MainView, name="main" ),
    path('registro/',views.login_request, name="registro" ),
    path('registro_residentes/',views.RegistroResidenteView, name="registro_residentes" ),
    #path('registro_vigilante/',views.RegistroVigilanteView, name="registro_vigilante" ),
    path('solicitud_token/',views.SolicitudTokenView, name="solicitud_token" ),
    path('sign_up_residente/<int:id>/',view.SignUpResidenteView.as_view(),name='sign_up_residente'),
    path('sign_up_vigilante/',view.SignUpVigilanteView.as_view(),name='sign_up_vigilante'),
    #path('', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    #path('accounts/', include ('accounts.urls', namespace='accounts')),
    #path('profiles/', include('profiles.urls')),
    #path('sign_in', SignInView.as_view(), name='sign_in'),
    path('registration/', include(registration_patterns)),
    path('upload/', include(upload_patterns)),
    #path('registro_residentes/',view.RegistroResidente,name='registro_residentes'),
    path('page/', include('pages.urls')),
    #path('profile/', include(profiles_patterns)),
    #path('register', views.register, name='register'),
    path('logout', views.logout, name='logout'),

    path('ckeditor/', include ('ckeditor_uploader.urls')),

    path('nuevo_usuario/',view.NuevoUsuarioView,name='nuevo_usuario'),
    #path('usuario_register/',view.UsuarioRegisterView.as_view(),name='usuario_register'),
    path('ajax/validar_email/',view.ajax_validar_email, name='ajax_validar_email'),
    #path('envio_mail_usuario/<int:id>',view.EnvioMailUsuarioView, name='envio_mail_usuario'),
    path('usuarios/',view.VerUsuariosView.as_view(), name='ver_usuarios'),
    path('editar_usuario/<int:pk>',view.EditarUsuariosView.as_view(), name='editar_usuario'),
    #path('signup/<int:id>',view.SignupView.as_view(), name='signup'),

    #path('accounts/login/', views.LoginView.as_view(), name='login'),
    #path('accounts/logout/', views.LogoutView.as_view(), name='logout'),
    path('accounts/password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('accounts/password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('reset_password',auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'),name='reset_password'),
    path('reset_password_sent',auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset.html'),name='password_reset_done'),
    path('reset/<uidb64>/token',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset_password_complete',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),

    path('pagina_administrador',view.PaginaAdministradorView.as_view(), name="pagina_administrador"),
    path('pagina_revisor',view.PaginaRevisorView.as_view(), name="pagina_revisor"),
    path('consejero',view.ConsejeroView.as_view(), name="consejero"),
    #path('residente',view.ResidenteView.as_view(), name="residente"),
    #path('vigilante',view.VigilanteView.as_view(), name="vigilante"),
    path('sistema',view.SistemaView.as_view(), name="sistema"),

    path('crear_usuarios',view.crea_user_perfil, name="crear_usuarios"),

    #path('coge_var_id',views.CogeVarIdView,name='coge_var_id'),
    #path('about/',AboutView.as_view(), name="about"),
    
    path('pagina_vigilancia',view.VigilanciaView.as_view(), name="pagina_vigilancia"),

    #path('consulta_accesos',view.AccesosView.as_view(), name="consulta_accesos"),
    #path('accesos',view.AccesosView.as_view(), name="accesos"),
    
    
    path('direcciona_salida_acceso_vehicular',view.DireccionaSalidaAccesoVehicularView, name="direcciona_salida_acceso_vehicular"),
    path('direcciona_salida_acceso_peatonal',view.DireccionaSalidaAccesoPeatonalView, name="direcciona_salida_acceso_peatonal"),
    
    path('direcciona_pagina_vigilancia_peatonal',view.DireccionaPaginaVigilanciaPeatonalView, name="direcciona_pagina_vigilancia_peatonal"),
    path('direcciona_pagina_vigilancia_vehicular',view.DireccionaPaginaVigilanciaVehicularlView, name="direcciona_pagina_vigilancia_vehicular"),

    #path('autorizaciones_peatonal_user/',view.AutorizacionesPeatonalUserView, name="autorizaciones_peatonal_user"),
    #path('autorizaciones_vehicular_user/',view.AutorizacionesVehicularUserView, name="autorizaciones_vehicular_user"),

    path('direcciona_salida_pagina_autorizaciones',view.DireccionaSalidaPaginaAutorizacionesView,name='direcciona_salida_pagina_autorizaciones'),
    path('pagina_autorizaciones/',view.PaginaAutorizacionesView.as_view(), name="pagina_autorizaciones"),
    path('pagina_accesos/',view.PaginaAccesosView.as_view(), name="pagina_accesos"),
    path('direcciona_salida_pagina_accesos',view.DireccionaSalidaPaginaAccesosView,name='direcciona_salida_pagina_accesos'),

    #path('autorizacion_ingreso_peatonal/',view.AutorizacionIngresoPeatonalView, name="autorizacion_ingreso"),
    path('autorizacion_plataforma_web_peatonal/',view.AutorizacionIngresoPlataformaWebPeatonalView, name="autorizacion_plataforma_web_peatonal"),
    path('autorizacion_plataforma_web_vehiculo/',view.AutorizacionIngresoPlataformaWebVehiculoView, name="autorizacion_plataforma_web_vehiculo"),

    #path('datos_autorizado',view.DatosAutorizadoView,name='datos_autorizado'),
    
    #path('direcciona_salida_pagina_autorizaciones',view.DireccionaSalidaPaginaAutorizacionesView,name='direcciona_salida_pagina_autorizaciones'),
    path('autorizaciones_peatonal_lista',view.AutorizacionesPeatonalListaView, name="autorizaciones_peatonal_lista"),
    path('crear_autorizado_peatonal/',view.CreaAutorizadoPeatonalView.as_view(),name='crear_autorizado_peatonal'),
    path('editar_autorizado_peatonal/<int:pk>/',view.EditaAutorizadoPeatonalView.as_view(),name='editar_autorizado_peatonal'),
    path('borrar_autorizado_peatonal/<int:pk>/',view.BorraAutorizadoPeatonalView.as_view(),name='borrar_autorizado_peatonal'),
    path('validar_autorizado_peatonal',view.ValidarAutorizadoPeatonalView,name='validar_autorizado_peatonal'),
    path('direcciona_salida_autorizaciones_peatonal',view.DireccionaSalidaAutorizacionesPeatonalView,name='direcciona_salida_autorizaciones_peatonal'),

    #path('autorizacion_ingreso_vehicular/',view.AutorizacionIngresoVehicularView, name="autorizacion_ingreso_vehicular"),
    path('autorizaciones_vehicular_lista/',view.AutorizacionesVehicularListaView, name="autorizaciones_vehicular_lista"),
    path('crear_autorizado_vehicular/',view.CreaAutorizadoVehicularView.as_view(),name='crear_autorizado_vehicular'),
    path('editar_autorizado_vehicular/<int:pk>/',view.EditaAutorizadoVehicularView.as_view(),name='editar_autorizado_vehicular'),
    path('borrar_autorizado_vehicular/<int:pk>/',view.BorraAutorizadoVehicularView.as_view(),name='borrar_autorizado_vehicular'),
    path('validar_autorizado_vehicular',view.ValidarAutorizadoVehicularView,name='validar_autorizado_vehicular'),
    path('direcciona_salida_autorizaciones_vehicular',view.DireccionaSalidaAutorizacionesVehicularView,name='direcciona_salida_autorizaciones_vehicular'),

    #path('guarda_datos_autorizado',view.GuardaDatosAutorizadoView, name="guarda_datos_autorizado"),
    #path('datos_autorizado_editar',view.DatosAutorizadoEditarView,name='datos_autorizado_editar'),
    #path('guarda_datos_autorizado_editar',view.GuardaDatosAutorizadoEditarView, name="guarda_datos_autorizado_editar"),
    #path('carga_datos_autorizado',view.CargaDatosAutorizadoView,name='carga_datos_autorizado'),
    #path('borra_autorizado',view.BorraAutorizadoView,name='borra_autorizado'),

    path('crear_autorizado_plataforma_web_peatonal',view.CreaAutorizadoPlataformaWebPeatonalView.as_view(),name='crear_autorizado_plataforma_web_peatonal'),
    path('editar_autorizado_plataforma_web_peatonal/<int:pk>/',view.EditaAutorizadoPlataformaWebPeatonalView.as_view(),name='editar_autoriszado_plataforma_web_peatonal'),
    path('borrar_autorizado_plataforma_web_peatonal/<int:pk>/',view.BorraAutorizadoPlataformaWebPeatonalView.as_view(),name='borrar_autorizado_plataforma_web_peatonal'),
    path('validar_autorizado_plataforma_web_peatonal',view.ValidarAutorizadoPlataformaWebPeatonalView,name='validar_autorizado_plataforma_web_peatonal'),

    path('crear_autorizado_plataforma_web_vehiculo',view.CreaAutorizadoPlataformaWebVehiculoView.as_view(),name='crear_autorizado_plataforma_web_vehiculo'),
    path('editar_autorizado_plataforma_web_vehiculo/<int:pk>/',view.EditaAutorizadoPlataformaWebPeatonalView.as_view(),name='editar_autorizado_plataforma_web_vehiculo'),
    path('borrar_autorizado_plataforma_web_vehiculo/<int:pk>/',view.BorraAutorizadoPlataformaWebPeatonalView.as_view(),name='borrar_autorizado_plataforma_web_vehiculo'),
    path('validar_autorizado_plataforma_web_vehiculo',view.ValidarAutorizadoPlataformaWebPeatonalView,name='validar_autorizado_plataforma_web_vehiculo'),
    
    path('ajax_switch_activo_autorizado_peatonal/',view.ajaxSwitchActivoAutorizadoPeatonalView,name='ajax_switch_activo_autorizado_peatonal'),
    path('ajax_switch_activo_autorizado_vehicular/',view.ajaxSwitchActivoAutorizadoVehicularView,name='ajax_switch_activo_autorizado_vehicular'),

    path('ajax_switch_permanente_autorizado_peatonal/',view.ajaxSwitchPermanenteAutorizadoPeatonalView,name='ajax_switch_permanente_autorizado_peatonal'),
    
    path('ajax_filtrar_apartamento/',view.ajaxFiltrarApartamentoView,name='ajax_filtrar_apartamento'),
    path('ajax_email_buscar_apartamento/',view.ajaxEmailBuscarApartamentoView,name='ajax_email_buscar_apartamento'),
           
    path('informes_revisor/<int:id>/',view.MensajePaginaEnConstruccionView, name="informes_revisor"),
    #path('direcciona_informes_revisor',view.DireccionaInformesRevisorView, name="direcciona_informes_revisor"),

   path('informacion_general',view.InformacionGeneralView.as_view(), name="informacion_general"),
    
    path('activos_fijos_lista',view.ActivosFijosListaView, name="activos_fijos_lista"),
    path('crea_activo_fijo',view.CreaActivoFijoView.as_view(), name="crea_activo_fijo"),
    path('edita_activo_fijo/<int:pk>/',view.EditaActivoFijoView.as_view(), name="edita_activo_fijo"),
    path('borra_activo_fijo/<int:pk>/',view.BorraActivoFijoView.as_view(), name="borra_activo_fijo"),
    #path('activos_fijos_uno/<int:id>/',view.ActivosFijosUnoView, name="activos_fijos_uno"),
    path('activos_fijos_detalle/<int:id>/',view.ActivosFijosDetalleView, name="activos_fijos_detalle"),
    path('activo_mantenimientos/',view.ActivoMantenimientos, name="activo_mantenimientos"),
    path('reporte_activos_fijos_xls',view.ReporteActivosFijosXlsView, name="reporte_activos_fijos_xls"),
    path('reporte_activos_fijos_pdf',view.ReporteActivosFijosPdfView, name="reporte_activos_fijos_pdf"),
    path('reporte_pagina_pdf_activos_fijos/<int:pagina>',view.ReportePaginasPdfActivosFijosView,name='reporte_pagina_pdf_activos_fijos'),
    path('carga_foto_activo_fijo/<int:id>',view.CargaFotoActivoFijoView,name='carga_foto_activo_fijo'),
    
    path('crea_prestamo_activo/',view.CreaPrestamoActivoView.as_view(),name='crea_prestamo_activo'),
    path('prestamos_activos_lista',view.PrestamosActivosListaView, name="prestamos_activos_lista"),
    path('reporte_prestamos_activos_fijos_pdf/<int:id>/<int:tipo_rep>',view.ReportePrestamosActivosFijosPdfView,name='reporte_prestamos_activos_fijos_pdf'),
    path('paginas_reporte_prestamo_pdf_activos_fijos/<int:pagina>',view.PaginasReportePrestamosActivosFijosPdfView,name='paginas_reporte_prestamo_pdf_activos_fijos'),
    path('borra_prestamo_activo_fijo/<int:pk>/',view.BorraPrestamoActivoFijoView.as_view(), name="borra_prestamo_activo_fijo"),
    
    path('crea_baja_activo/',view.CreaBajaActivoView.as_view(),name='crea_baja_activo'),
    path('bajas_activos_lista',view.BajasActivosListaView, name="bajas_activos_lista"),
    path('reporte_bajas_activos_fijos_pdf/<int:id>/<int:tipo_rep>',view.ReporteBajasActivosFijosPdfView,name='reporte_bajas_activos_fijos_pdf'),
    path('paginas_reporte_bajas_pdf_activos_fijos/<int:pagina>',view.PaginasReporteBajasActivosFijosPdfView,name='paginas_reporte_bajas_pdf_activos_fijos'),
    path('borra_baja_activo_fijo/<int:pk>/',view.BorraBajaActivoFijoView.as_view(), name="borra_baja_activo_fijo"),

    
    #path('reporte_prestamos_activos_fijos_xls',view.ReportePrestamosActivosXLSView, name="reportes_prestamos_activos_fijos_xls"),
    
    path('lista_mantenimientos',view.MantenimientosListaView,name='lista_mantenimientos'),
    path('mantenimientos_detalle/<int:id>/',view.MantenimientosDetalleView,name='mantenimientos_detalle'),
    path('crea_mantenimiento/',view.CreaMantenimientoView.as_view(),name='crea_mantenimiento'),
    path('edita_mantenimiento/<int:pk>/',view.EditaMantenimientoView.as_view(),name='edita_mantenimiento'),
    path('borra_mantenimiento/<int:pk>/',view.BorraMantenimientoView.as_view(),name='borra_mantenimiento'),
    path('activo_mantenimientos/<int:pk>/',view.ActivoMantenimientos,name='activo_mantenimientos'),
    path('borra_anexo_mantenimiento/<int:pk>/',view.BorraAnexoMantenimientoView.as_view(),name='borra_anexo_mantenimiento'),
    path('mantenimientos_redireccionar',view.MantenimientosRedireccionarView,name='mantenimientos_redireccionar'),
    #path('imprimir_mantenimientos',view.ImprimirMantenimientosView,name='imprimir_mantenimientos'),
    path('reporte_mantenimientos_xls',view.ReporteMantenimientosXlsView,name='reporte_mantenimientos_xls'),
    path('reporte_mantenimientos_pdf',view.ReporteMantenimientosPdfView,name='reporte_mantenimientos_pdf'),
    path('paginas_reporte_mantenimientos_pdf/<int:pagina>',view.PaginasReporteMantenimientosPdfView,name='paginas_reporte_mantenimientos_pdf'),

    
    #path('activos_fijos_lista/<int:id>',views.ActivosFijosUnoView,name='activos_fijos_lista'),
    #path('adicionar_mantenimiento/<int:id>/',view.AdicionarMantenimientoView,name="adicionar_mantenimiento"),
    #path('verificar_mantenimientos/<int:id>/',view.VerficarMantenimientosView, name="verificar_mantenimientos"),
    #path('activos_fijos_adicionar',view.ActivosFijosAdicionarView, name="activos_fijos_adicionar"),
    
    path('lista_proyectos',view.ListaProyectosView,name='lista_proyectos'),
    path('proyecto_detalle/<int:id>/',view.ProyectoDetalleView,name='proyecto_detalle'),
    path('crear_proyecto/',view.CreaProyectoView.as_view(),name='crear_proyecto'),
    path('edita_proyecto/<int:pk>/',view.EditaProyectoView.as_view(),name='edita_proyecto'),
    path('borra_proyecto/<int:pk>/',view.BorraProyectoView.as_view(),name='borra_proyecto'),
    path('borra_anexo_proyecto/<int:pk>/',view.BorraAnexoProyectoView.as_view(),name='borra_anexo_proyecto'),
    path('borra_anexo_proponente_proyecto/<int:pk>/',view.BorraAnexoProponenteProyectoView.as_view(),name='borra_anexo_proponente_proyecto'),
    path('adiciona_proponente_proyecto/',view.AdicionaProponenteProyectoView.as_view(),name='adiciona_proponente_proyecto'),
    path('guarda_idproyecto',view.GuardaIdProyectoView,name='guarda_idproyecto'),
    path('ajax_switch_aprobado_proyecto/',view.ajaxSwitchAprobadoProyectoView,name='ajax_switch_aprobado_proyecto'),
    #path('filtro_proyecto',view.ListaProyectosFilterView,name='filtro_proyecto'),
    path('reporte_proyectos_xls',view.ReporteProyectosXlsView,name='reporte_proyectos_xls'),
    path('reporte_proyectos_pdf',view.ReporteProyectosPdfView,name='reporte_proyectos_pdf'),
    path('paginas_reporte_proyectos_pdf/<int:pagina>',view.PaginasReporteProyectosPdfView,name='paginas_reporte_proyectos_pdf'),
    
    #path('pasa_proponente_a_proveedor/'.view.PasaProponenteProveedorView,name='pasa_proponente_a_proveedor'),

    path('lista_obras',view.ListaObrasView,name='lista_obras'),
    path('obra_detalle/<int:id>/',view.ObraDetalleView,name='obra_detalle'),
    path('crea_obra/',view.CreaObrasView.as_view(),name='crea_obra'),
    path('edita_obra/<int:pk>/',view.EditaObrasView.as_view(),name='edita_obra'),
    path('borra_obra/<int:pk>/',view.BorraObrasView.as_view(),name='borra_obra'),
    path('borra_anexo_obra/<int:pk>/',view.BorraAnexoObraView.as_view(),name='borra_anexo_obra'),

    path('crea_avance_obra/<int:id>/',view.CreaAvanceObraView.as_view(),name='crea_avance_obra'),
    path('edita_avance_obra/<int:pk>/',view.EditaAvanceObraView.as_view(),name='edita_avance_obra'),
    path('borra_avance_obra/<int:pk>/',view.BorraAvanceObraView.as_view(),name='borra_avance_obra'),
    path('borra_anexo_avance_obra/<int:pk>/',view.BorraAnexoAvanceObraView.as_view(),name='borra_anexo_avance_obra'),
    path('guarda_idobra',view.GuardaIdObraView,name='guarda_idobra'),
    #path('imprimir_obras',view.ImprimirObrasView,name='imprimir_obras'),
    path('reporte_obras_xls',view.ReporteObrasXlsView,name='reporte_obras_xls'),
    path('reporte_obras_pdf',view.ReporteObrasPdfView,name='reporte_obras_pdf'),
    path('paginas_reporte_obras_pdf/<int:pagina>',view.PaginasReporteObrasPdfView,name='paginas_reporte_obras_pdf'),


    path('lista_reparaciones',view.ListaReparacionesView,name='lista_reparaciones'),
    path('reparaciones_detalle/<int:id>/',view.ReparacionesDetalleView,name='reparaciones_detalle'),
    path('crea_reparacione/',view.CreaReparacionesView.as_view(),name='crea_reparacion'),
    path('edita_reparacion/<int:pk>/',view.EditaReparacionesView.as_view(),name='edita_reparacion'),
    path('borra_reparacion/<int:pk>/',view.BorraReparacionesView.as_view(),name='borra_reparacion'),
    path('borra_anexo_reparacion/<int:pk>/',view.BorraAnexoReparacionView.as_view(),name='borra_anexo_reparacion'),
    path('reporte_reparaciones_xls',view.ReporteReparacionesXlsView,name='reporte_reparaciones_xls'),
    path('reporte_reparaciones_pdf',view.ReporteReparacionesPdfView,name='reporte_reparaciones_pdf'),
    path('paginas_reporte_reparaciones_pdf/<int:pagina>',view.PaginasReporteReparacionesPdfView,name='paginas_reporte_reparaciones_pdf'),

    path('proveedores',view.PaginaProveedoresView.as_view(), name="proveedores"),
    path('lista_proveedores',view.ListaProveedoresView, name="lista_proveedores"),
    path('proveedor_detalle/<int:id>/',view.ProveedorDetalleView, name='proveedor_detalle'),
    path('crea_proveedor/',view.CreaProveedorView.as_view(),name='crea_proveedor'),
    path('edita_proveedor/<int:pk>/',view.EditaProveedorView.as_view(),name='edita_proveedor'),
    path('borra_proveedor/<int:pk>/',view.BorraProveedorView.as_view(),name='borra_proveedor'),
    path('reporte_proveedores_xls',view.ReporteProveedoresXlsView,name='reporte_proveedores_xls'),
    path('reporte_proveedores_pdf',view.ReporteProveedoresPdfView,name='reporte_proveedores_pdf'),
    path('paginas_reporte_proveedores_pdf/<int:pagina>',view.PaginasReporteProveedoresPdfView,name='paginas_reporte_proveedores_pdf'),
        
    ## Guarda estos datos en una variable global para poder cagar un initial en la forma
    path('guarda_identificacion',view.GuardaIdentificacionView,name='guarda_identificacion'),
    path('guarda_tipo_identificacion',view.GuardaTipoIdentificacionView,name='guarda_tipo_identificacion'),
    path('guarda_numero_contrato',view.GuardaNumeroContratoView,name='guarda_numero_contrato'),
    path('guarda_fecha_contrato',view.GuardaFechaContratoView,name='guarda_fecha_contrato'),
    path('guarda_nombre_activo',view.GuardaNombreActivoView,name='guarda_nombre_activo'),

    path('lista_proponentes',view.ListaProponentesView, name="lista_proponentes"),
    path('proponente_detalle/<int:id>',view.ProponentesDetalleView, name="proponente_detalle"),
    path('crea_proponente/',view.CreaProponenteView.as_view(),name='crea_proponente'),
    path('edita_proponente/<int:pk>/',view.EditaProponenteView.as_view(),name='edita_proponente'),
    path('borra_proponente/<int:pk>/',view.BorraProponenteView.as_view(),name='borra_proponente'),
    path('proponente_a_proveedor/<int:id>/',view.ProponenteProveedodorView,name='proponente_a_proveedor'),
    path('proponente_proyecto_a_proveedor/<int:id>/',view.ProponenteProyectoProveedodorView,name='proponente_proyecto_a_proveedor'),
    #path('crea_proponente_proyecto/',view.CreaProponenteProyectoView.as_view(),name='crea_proponente_proyecto'),
    path('borra_proponente_proyecto/<int:pk>/',view.BorraProponenteProyectoView.as_view(),name='borra_proponente_proyecto'),
    path('edita_proponente_proyecto/<int:pk>/',view.EditaProponenteProyectoView.as_view(),name='edita_proponente_proyecto'),
    #path('borra_proponente_proyecto/<int:pk>/',view.BorraProponenteProyectoView.as_view(),name='borra_proponete_proyecto'),
    path('borra_anexo_proponente_proyecto/<int:pk>/',view.BorraAnexoProponenteProyectoView.as_view(),name='borra_anexo_proponente_proyecto'),
    path('ajax_switch_seleccionado_proponente/',view.ajaxSwitchSeleccionadoProponenteView,name='ajax_switch_seleccionado_proponente'),
    path('imprimir_proponentes_xls/',view.ImprimirProponentesXlsView,name='imprimir_proponentes_xls'),
    path('reporte_proponentes_pdf/',view.ReporteProponentesPdfView,name='reporte_proponentes_pdf'),
    path('paginas_reporte_proponentes_pdf/<int:pagina>/',view.PaginasReporteProponentesPdfView,name='paginas_reporte_proponentes_pdf'),
    #path('crear_servicio/',view.DatosServicioView,name='crear_servicio'),
    #path('guarda_datos_servicio/',view.GuardaDatosServicioView,name='guarda_datos_servicio'),

    path('crear_servicio/',view.CreaServicioView.as_view(),name='crear_servicio'),
    path('crear_tipo_proyecto/',view.CreaTipoProyectoView.as_view(),name='crear_tipo_proyecto'),
    path('crear_tipo_contrato/',view.CreaTipoContratoView.as_view(),name='crear_tipo_contrato'),
    path('crear_tipo_activo/',view.CreaTipoActivoFijoView.as_view(),name='crear_tipo_activo'),
    path('crear_tipo_asamblea/',view.CreaTipoAsambleaView.as_view(),name='crear_tipo_asamblea'),
    path('guarda_fecha_asamblea',view.GuardaFechaAsambleaView, name="guarda_fecha_asamblea"),
    path('direcciona_salida_pagina_asamblea',view.DireccionaSalidaPaginaAsambleaView,name='direcciona_salida_pagina_asamblea'),

    path('lista_contratos',view.ContratosListaView, name="lista_contratos"),
    path('contratos_detalle/<int:id>/',view.ContratosDetalleView, name="contratos_detalle"),
    #path('lista_contratos',view.ContratosListaView, name="lista_contratos"),
    #path('lista_contratos',view.ListaContratosView, name="lista_contratos"),
    path('crea_contrato/',view.CreaContratoView.as_view(),name='crea_contrato'),
    path('edita_contrato/<int:pk>/',view.EditaContratoView.as_view(),name='edita_contrato'),
    path('borra_contrato/<int:pk>/',view.BorraContratoView.as_view(),name='borra_contrato'),
    path('reporte_contratos_xls',view.ReporteContratosXlsView,name='reporte_contratos_xls'),
    path('reporte_contratos_pdf',view.ReporteContratosPdfView,name='reporte_contratos_pdf'),
    path('paginas_reporte_contratos_pdf/<int:pagina>',view.PaginasReporteContratosPdfView,name='paginas_reporte_contratos_pdf'),
    
    #tView,name='contrato'),
    
    #path('asamblea',AsambleaView.as_view(), name="asamblea"),
    
    #path('blog',view.BlogView.as_view(),name='blog'),
        
    path('pagina_alertas',view.PaginaAlertasView.as_view(), name="pagina_alertas"),
    path('alerta_recibo_energia',view.AlertaReciboEnergiaView, name="alerta_recibo_energia"),
    path('alerta_recibo_agua',view.AlertaReciboAguaView, name="alerta_recibo_agua"),
    path('alerta_recibo_gas',view.AlertaReciboGasView, name="alerta_recibo_gas"),
    
    path('acceso_peatonal',view.AccesoPeatonalView.as_view(), name="acceso_peatonal"),
    path('acceso_peatonal_lista',view.AccesoPeatonalListaView, name="acceso_peatonal_lista"),
    path('ingreso_peatonal_busqueda',view.IngresoPeatonalBusquedaView, name="ingreso_peatonal_busqueda"),
    #path('ingreso_peatonal_busqueda_parametro',view.IngresoPeatonalBusquedaParametroView, name="ingreso_peatonal_busqueda_parametro"),
    path('crear_ingreso_peatonal',view.CreaIngresoPeatonalView.as_view(), name="crear_ingreso_peatonal"),
    path('guarda_datos_ingreso_peatonal',view.GuardaDatosIngresoPeatonalView, name="guarda_datos_ingreso_peatonal"),
    path('guarda_datos_ingreso_peatonal_autorizado',view.GuardaDatosIngresoPeatonaAutorizadoView, name="guarda_datos_ingreso_peatonal_autorizado"),
    path('crear_visitante',view.CrearVisitanteView.as_view(), name="crear_visitante"),
    path('datos_visitante',view.DatosVisitanteView,name='datos_visitante'),
    #path('datos_ingreso_peatonal',view.DatosIngresoPeatonalView,name='datos_ingreso_peatonal'),
    path('guarda_datos_ingreso_peatonal',view.GuardaDatosIngresoPeatonalView,name='guarda_datos_ingreso_peatonal'),
    path('guarda_datos_visitante',view.GuardaDatosVisitanteView,name='guarda_datos_visitante'),
    path('guarda_identificacion_visitante',view.GuardaIdentificacionVisitanteView,name='guarda_identificacion_visitante'),
    path('salida_peatonal',view.SalidaPeatonalView,name='salida_peatonal'),
    #path('filtro_ingresos_peatonal',view.IngresoPeatonalBusquedaParametroView,name='filtro_ingresos_peatonal'),
    path('reporte_ingreso_peatonal_xls',view.ReporteIngresoPeatonalXlsView,name='reporte_ingreso_peatonal_xls'),
    
    path('acceso_vehicular_lista',view.AccesoVehicularListaView, name="acceso_vehicular_lista"),
    path('acceso_vehicular',view.AccesoVehicularView, name="acceso_vehicular"),
    path('ingreso_vehicular_busqueda',view.IngresoVehicularBusquedaView, name="ingreso_vehicular_busqueda"),
    path('ingreso_vehicular_busqueda_parametro',view.IngresoVehicularBusquedaParametroView, name="ingreso_vehicular_busqueda_parametro"),
    path('crear_ingreso_vehicular',view.CreaIngresoVehicularView.as_view(), name="crear_ingreso_vehicular"),
    #path('datos_ingreso_vehicular',view.DatosIngresoVehicularView, name="datos_ingreso_vehicular"),
    path('guarda_datos_ingreso_vehicular',view.GuardaDatosIngresoVehicularView, name="guarda_datos_ingreso_vehicular"),
    path('guarda_datos_ingreso_vehicular_autorizado',view.GuardaDatosIngresoPeatonaAutorizadoView, name="guarda_datos_ingreso_vehicular_autorizado"),
    path('crear_visitante_vehicular',view.CrearVisitanteView.as_view(), name="crear_visitante_vehicular"),
    path('datos_visitante_vehicular',view.DatosVisitanteVehicularView,name='datos_visitante_vehicular'),
    path('guarda_datos_visitante_vehicular',view.GuardaDatosVisitanteVehicularView,name='guarda_datos_visitante_vehicular'),
    path('salida_vehicular',view.SalidaVehicularView,name='salida_vehicular'),
    path('reporte_ingreso_vehicular_xls',view.ReporteIngresoVehicularXlsView,name='reporte_ingreso_vehicular_xls'),

    #path('calendario', CalendarioView.as_view(), name='calendario'),

    path('correspondencia', view.PaginaCorrespondenciaView.as_view(), name='correspondencia'),
    path('datos_correspondencia',view.DatosCorrespondenciaView,name='datos_correspondencia'),
    path('guarda_datos_correspondencia',view.GuardaDatosCorrespondenciaView,name='guarda_datos_correspondencia'),
    path('crea_correspondencia',view.CreaCorrespondenciaView.as_view(), name='crea_correspondencia'),
    path('lista_correspondencia',view.CorrespondenciaListView, name='lista_correspondencia'),
    #path('lista_correspondencia_user/<int:id>/',view.CorrespondenciaListUserView, name='lista_correspondencia_user'),
    #path('lista_correspondencia_admin/<int:id>/',view.CorrespondenciaListAdminView, name='lista_correspondencia_admin'),
    #path('filtros_correspondencia/',view.CorrespondenciaListFilterView.as_view(), name='filtros_correspondencia'),
    path('consulta_correspondencia',view.CorrespondenciaConsultaView, name='consulta_correspondencia'),
    path('entregas_correspondencia',view.EntregasCorrespondenciaView, name='entregas_correspondencia'),
    path('mensaje_correspondencia',view.MensajeCorrespondenciaView.as_view(),name='mensaje_correspondencia'),
    path('reporte_correspondencia_xls',view.ReporteCorrespondenciaXlsView,name='reporte_correspondencia_xls'),

    path('direcciona_salida_correspondencia',view.DireccionaCorrespondenciaView, name="direcciona_salida_correspondencia"),
    #path('mantenimientos/<int:id>',views.MantenimientosView,name='mantenimientos'),

    path('importar_xls_apartamentos',views.import_xls_apartamentos,name='importar_xls_apartamentos'),
    path('importar_xls_residentes',views.import_xls_residentes,name='importar_xls_residentes'),
    path('importar_xls_parqueaderos',views.import_xls_parqueaderos,name='importar_xls_parqueaderos'),
    
    path('crea_parqueadero/<int:idinterior>/<int:idapartamento>/',view.CrearParqueaderoView.as_view(),name='crea_parqueadero'),
    path('borrar_parqueadero/<int:id>/',view.BorrarParqueaderoView,name='borrar_parqueadero'),
    path('editar_parqueadero/<int:pk>/',view.EditarParqueaderoView.as_view(),name='editar_parqueadero'),
    
    path('crea_vehiculo/<int:idinterior>/<int:idapartamento>/',view.CrearVehiculoView.as_view(),name='crea_vehiculo'),
    path('borrar_vehiculo/<int:id>',view.BorraVehiculoView,name='borrar_vehiculo'),
    path('editar_vehiculo/<int:pk>/',view.EditarVehiculoView.as_view(),name='editar_vehiculo'),

    path('crea_mascota/<int:idinterior>/<int:idapartamento>/',view.CrearMascotaView.as_view(),name='crea_mascota'),
    path('borrar_mascota/<int:id>/',view.BorrarParqueaderoView,name='borrar_mascota'),
    path('editar_mascota/<int:pk>/',view.EditarMascotaView.as_view(),name='editar_mascota'),

    path('pagina_informacion_residentes',views.PaginaInformacionResidentesView.as_view(),name='pagina_informacion_residentes'),
    #path('envio_mail_residente',views.EnvioMailResidenteView,name='envio_mail_residente'),
    path('informacion_residentes',views.InformacionResidentesView,name='informacion_residentes'),
    path('solicitudes_residentes',views.SolicitudesResidentesView,name='solicitudes_residentes'),
    path('solicitudes_residentes_uno/<int:id>/',views.SolicitudesResidentesUnoView,name='solicitudes_residentes_uno'),
    #path('informacion_solicitudes_residentes',views.InformacionSolicitudesResidentesView,name='informacion_solicitudes_residentes'),
    path('informacion_residente_detalle/<int:id>/',views.InformacionResidenteDetalleView,name='informacion_residente_detalle'),
    #path('informacion_residente/<int:id>',view.InformacionResidenteView.as_view(),name='informacion_residente'),ajax_switch_envio_staff
    #path('crear_residente_uno',view.CrearResidenteUnoView.as_view(),name='crear_residente_uno'),
    path('crea_residente',view.CrearResidenteView.as_view(),name='crea_residente'),
    path('editar_residente/<int:pk>/',view.EditarResidenteView.as_view(),name='editar_residente'),
    path('crear_residente_temporal/',view.CrearResidenteTempView.as_view(),name='crear_residente_temporal'),
    path('adicionar_residente_desde_temp/<int:id>/',view.AdicionarResidenteDesdeTemp,name='adicionar_residente_desde_temp'),
    path('borrar_residente/<int:id>/',view.BorrarResidenteView,name='borrar_residente'),
    path('seleccion_filtro_apartamento_residentes',view.SeleccionParametroApartamentoResidentesView,name='seleccion_filtro_apartamento_residentes'),
    path('informacion_residentes_filtro_apartamento/',view.InformacionResidentesFiltroApartamentoView,name='informacion_residentes_filtro_apartamento'),
    
    path('seleccion_email_anexo/<int:id>/<int:tipomail>',view.SeleccionEmailAnexoView,name='seleccion_email_anexo'),
    path('envio_email_residentes_filtro',view.EnvioEmailResidentesFiltroView.as_view(),name='envio_email_residentes_filtro'),
    path('envio_email_anexo_residentes_filtro',view.EnvioEmailAnexoResidentesFiltroView.as_view(),name='envio_email_anexo_residentes_filtro'),
    #path('pone_variable_anexo/<int:id>',view.PoneVariableAnexo.as_view(),name='pone_variable_anexo'),
    path('envio_email_un_residente/',view.EnvioEmailUnResidenteView.as_view(),name='envio_email_un_residente'),
    path('envio_email_anexo_un_residente/',view.EnvioEmailAnexoUnResidenteView.as_view(),name='envio_email_anexo_un_residente'),
    path('envio_correos_masivos_residentes',view.EnvioCorreosMasivosResidentesView,name='envio_correos_masivos_residentes'),
    path('ajax_switch_marca_correo_residentes/',view.ajaxSwitchMarcaResidentesCorreosView,name='ajax_switch_marca_correo_residentes'),
    path('ajax_switch_marca_token_residentes',view.ajaxSwitchTokenResidentesView,name='ajax_switch_marca_token_residentes'),
    path('marca_envio_correo_residentes',view.MarcaEnvioCorreoResidentesView,name='marca_envio_correo_residentes'),

    path('pagina_envio_tokens',view.EnvioTokensResidentesView,name='pagina_envio_tokens'),
    path('marca_tokens_residentes',view.MarcaTokensResidentesView,name='marca_tokens_residentes'),
    path('generar_tokens',view.GenerarTokensView,name='generar_tokens'),

    #path('paqueadero_residente',view.CrearResidenteView.as_view(),name='parqueadero_residente'),
    #path('vehiculo_residente',view.CrearResidenteView.as_view(),name='vehiculo_residente'),
    #path('mascota_residente',view.CrearResidenteView.as_view(),name='mascota_residente'),

    #path('otros_residente',view.CrearResidenteOtroView.as_view(),name='otro_residente'),
    #path('deposito_residente',view.CrearResidenteView.as_view(),name='deposito_residente'),
    
    path('pagina_zonas_comunes',view.PaginaZonasComunesView.as_view(), name="pagina_zonas_comunes"),
    path('lista_zonas_comunes',view.ZonasComunesListaView, name="lista_zonas_comunes"),
    path('crear_zona_comun',view.CreaZonaComunView.as_view(), name="crear_zona_comun"),
    path('borrar_zona_comun/<int:pk>/',view.BorraZonaComunView.as_view(), name="borrar_zona_comun"),
    path('editar_zona_comun/<int:pk>/',view.EditaZonaComunView.as_view(), name="editar_zona_comun"),
    path('carga_foto_zonas_comunes/<int:id>',view.CargaFotoZonaComunView,name='carga_foto_zonas_comunes'),
    #path('ajax_switch_arrienda_zonas_comunes/',view.ajaxSwitchArriendaZonasComunesView,name='ajax_switch_arrienda_zonas_comunes'),

    path('reserva_zonas_comunes/<int:id>/',view.ReservaZonasComunesView,name='reserva_zonas_comunes'),
    path('direcciona_reserva_zonas_comunes/',view.DireccionaReservaZonasComunesView,name='direcciona_reserva_zonas_comunes'),
    path('consulta_reserva_zonas_comunes_administrador/<int:id>',view.ConsultaReservaZonasComunesAdministradorView,name='consulta_reserva_zonas_comunes_administrador'),
    
    path('pagar_reserva/<int:id>',view.PagoReservaZonasComunesView,name='pagar_reserva'),
    
    #path('datos_reserva_zonas_comunes',view.DatosReservaZonasComunesView,name='datos_reserva_zonas_comunes'),
    #path('reserva_zonas_comunes/<int:id>',view.ReservaZonasComunesView,name='reserva_zonas_comunes'),
    #path('filtro_zonas_comunes/<int:id>',view.FiltroZonasComunesView,name='filtro_zonas_comunes'),
    path('crear_reserva_zonas_comunes/<int:id>/',view.CrearReservaZonasComunesView.as_view(),name='crear_reserva_zonas_comunes'),
    path('edita_reserva_zonas_comunes/<int:pk>/',view.EditaReservaZonasComunesView.as_view(),name='edita_reserva_zonas_comunes'),
    path('confirma_reserva_zonas_comunes/<int:id>/',view.ConfirmaReservaZonasComunesView,name='confirma_reserva_zonas_comunes'),
    path('borra_reserva_zonas_comunes/<int:pk>/',view.BorraReservaZonasComunesView.as_view(),name='borra_reserva_zonas_comunes'),
    path('filtrar_fecha_reserva_zonas_comunes',view.FiltrarFechaReservaZonasComunes,name='filtrar_fecha_reserva_zonas_comunes'),
    #path('borrar_reserva_zonas_comunes/<int:id>',view.BorrarReservaZonasComunes,name='borrar_reserva_zoneuas_comunes'),
    #path('informacion_residentes',InformacionresidentesView,name='informacion_residentes'),
    path('direcciona_pagina_zonas_conunes',view.DireccionaPagoReservaZonasComunes,name='direcciona_pagina_zonas_conunes'),

    #path('', generic.TemplateView.as_view(template_name="core/index.html"), name="index"),
    
    #path('guardar_foto',view.GuardarFoto, name="guardar_foto"),
    #path('ver_foto',view.VerFoto, name="ver_foto"),
    path('ver_foto_vehiculo',view.VerFotoVehiculo, name="ver_foto_vehiculo"),
    
    path('pagina_consejo',view.PaginaConsejoView.as_view(),name='pagina_consejo'),
    path('lista_reuniones_consejo',view.ListaReunionConsejoView,name='lista_reuniones_consejo'),
    path('crea_reunion_consejo/',view.CreaReunionConsejoView.as_view(),name='crea_reunion_consejo'),
    path('edita_reunion_consejo/<int:pk>/',view.EditaReunionConsejoView.as_view(),name='edita_reunion_consejo'),
    path('borra_reunion_consejo/<int:pk>/',view.BorraReunionConsejoView.as_view(),name='borra_reunion_consejo'),
    path('detalle_reunion_consejo/<int:id>/',view.DetalleReunionConsejoView,name='detalle_reunion_consejo'),

    path('reportes_reuniones_consejo_xls',view.ReportesReunionesConsejoXlsView.as_view(),name='reportes_reuniones_consejo_xls'),
    path('tipo_reporte_reuniones_consejo_pdf',view.TipoReporteReunionesConsejoPdfView.as_view(),name='tipo_reporte_reuniones_consejo_pdf'),
    #path('reportes_reuniones_consejo_detalle_pdf/<int:id>',view.ReportesReunionesConsejoDetallePdfView.as_view(),name='reportes_reuniones_consejo_detalle_pdf'),
    path('ajax_guarda_id_reunion',view.AjaxGuardaIdReunionView,name='ajax_guarda_id_reunion'),
    #path('reportes_reuniones_consejo_lista_pdf/<int:detalle>/',view.ReporteReunionesConsejoListaPdfView,name='reportes_reuniones_consejo_lista_pdf'),
    #path('reportes_reuniones_consejo_detalle_pdf/<int:detalle>/',view.ReporteReunionesConsejoDetallePdfView,name='reportes_reuniones_consejo_detalle_pdf'),

    path('reporte_reuniones_consejo_xls/<int:tipo>/<int:estado>/',view.ReporteReunionesConsejoXlsView,name='reporte_reuniones_consejo_xls'),
    path('reporte_reuniones_consejo_pdf/<int:tipo>/<int:estado>/',view.ReporteReunionesConsejoPdfView,name='reporte_reuniones_consejo_pdf'),
    path('reporte_pendientes_consejo_pdf/',view.ReportePendientesConsejoPdfView.as_view(),name='reporte_pendientes_consejo_pdf'),
    path('reporte_pendientes_recomendaciones_revisor_fiscal_pdf',view.ReportePendientesRecomendacionesRevisorPdfView,name='reporte_pendientes_recomendaciones_revisor_fiscal_pdf'),
    path('reporte_pendientes_decisiones_asamblea_pdf',view.ReportePendientesDecisionesAsambleaPdfView.as_view(),name='reporte_pendientes_decisiones_asamblea_pdf'),
    path('paginas_reporte_reuniones_consejo_pdf/<int:pagina>/<int:tipo>',view.PaginasReporteReunionConsejoPdfView,name='paginas_reporte_reuniones_consejo_pdf'),

    path('reunion_consejo_contenido/<int:id>/',view.ReunionConsejoContenidoView,name='reunion_consejo_contenido'),
    path('imprimir_acta_reunion_consejo/<int:id>/',view.MensajePaginaEnConstruccionView,name='imprimir_acta_reunion_consejo'),
    #path('actas_consejo/<int:id>/',view.MensajePaginaEnConstruccionView, name="actas_consejo"),
    path('crea_decision_consejo/<int:id>/',view.CreaDecisionConsejoView.as_view(),name='crea_decision_consejo'),
    path('edita_decision_consejo/<int:pk>/',view.EditaDecisionConsejoView.as_view(),name='edita_decision_consejo'),
    path('borra_decision_consejo/<int:pk>/',view.BorraDecisionConsejoView.as_view(),name='borra_decision_consejo'),
    
    path('crea_compromiso_consejo/<int:id>/',view.CreaCompromisoConsejoView.as_view(),name='crea_compromiso_consejo'),
    path('borra_compromiso_consejo/<int:pk>/',view.BorraCompromisoConsejoView.as_view(),name='borra_compromiso_consejo'),
    path('edita_compromiso_consejo/<int:pk>/',view.EditaCompromisoConsejoView.as_view(),name='edita_compromiso_consejo'),
    path('compromiso_detalle/<int:id>/',view.CompromisoDetalleView,name='compromiso_detalle'),
    path('aplica_compromiso_consejo/<int:pk>/',view.AplicaCompromisoConsejoView.as_view(),name='aplica_compromiso_consejo'),


    path('borra_anexo_reunion_consejo/<int:pk>/',view.BorraAnexoReunionConsejoView.as_view(),name='borra_anexo_reunion_consejo'),
    path('publicar_reunion_consejo/<int:id>/',view.PublicaReunionConsejoView,name='publicar_reunion_consejo'),
    
    path('lista_comite_convivencia/',view.ListaComiteConvivenciaView,name='lista_comite_convivencia'),
    path('crea_comite_convivencia/',view.CreaComiteConvivenciaView.as_view(),name='crea_comite_convivencia'),
    path('edita_comite_convivencia/<int:pk>/',view.EditaComiteConvivenciaView.as_view(),name='edita_comite_convivencia'),
    path('borra_comite_convivencia/<int:pk>/',view.BorraComiteConvivenciaView,name='borra_comite_convivencia'),
    path('carga_foto_comite_convivencia/<int:id>',view.CargaFotoComiteConvivenciaView,name='carga_foto_comite_convivencia'),

    path('ajax_switch_envio_convivencia/',view.ajaxSwitchEnvioConvivenciaView,name='ajax_switch_envio_convivencia'),
    path('ajax_switch_activo_convivencia/',view.ajaxSwitchActivoConvivenciaView,name='ajax_switch_activo_convivencia'),
    path('ajax_switch_publicar_convivencia/',view.ajaxSwitchPublicarConvivenciaView,name='ajax_switch_publicar_convivencia'),
    path('ajax_switch_comunidad_convivencia/',view.ajaxSwitchComunidadConvivenciaView,name='ajax_switch_comunidad_convivencia'),

    path('lista_miembros_consejo/',view.ListaMiembrosConsejoView,name='lista_miembros_consejo'),
    path('crea_miembro_consejo/',view.CreaMiembroConsejoView.as_view(),name='crea_miembro_consejo'),
    path('edita_miembro_consejo/<int:pk>/',view.EditaMiembroConsejoView.as_view(),name='edita_miembro_consejo'),
    path('borra_miembro_consejo/<int:pk>/',view.BorraMiembroConsejoView,name='borra_miembro_consejo'),
    path('carga_foto_miembro_consejo/<int:id>',view.CargaFotoMiembroConsejoView,name='carga_foto_miembro_consejo'),

   
    path('ajax_switch_envio_consejero/',view.ajaxSwitchEnvioConsejeroView,name='ajax_switch_envio_consejero'),
    path('ajax_switch_activo_consejero/',view.ajaxSwitchActivoConsejeroView,name='ajax_switch_activo_consejero'),
    path('ajax_switch_publicar_consejero/',view.ajaxSwitchPublicarConsejeroView,name='ajax_switch_publicar_consejero'),
    path('ajax_switch_comunidad_consejero/',view.ajaxSwitchComunidadConsejeroView,name='ajax_switch_comunidad_consejero'),
    
    path('lista_informes_revisor',view.ListaInformesRevisorView,name='lista_informes_revisor'),
    path('informe_revisor_detalle/<int:id>/',view.InformeRevisorDetalleView,name='informe_revisor_detalle'),
    path('informe_revisor_contenido/<int:id>/',view.InformeRevisorContenidoView,name='informe_revisor_contenido'),
    path('crea_informe_revisor',view.CreaInformeRevisorView.as_view(),name='crea_informe_revisor'),
    path('edita_informe_revisor/<int:pk>/',view.EditaInformeRevisorView.as_view(),name='edita_informe_revisor'),
    path('borra_informe_revisor/<int:pk>/',view.BorraInformeRevisorView.as_view(),name='borra_informe_revisor'),
    #path('imprimir_informe_revisor/<int:id>/',view.MensajePaginaEnConstruccionView,name='imprimir_informe_revisor'),
    path('publicar_informe_revisor/<int:id>/',view.MensajePaginaEnConstruccionView,name='publicar_informe_revisor'),
    path('borra_anexo_informe_revisor/<int:pk>/',view.BorraAnexoInformeRevisorView.as_view(),name='borra_anexo_informe_revisor'),
    path('recomendacion_detalle/<int:id>/',view.RecomendacionDetalleView,name='recomendacion_detalle'),
    path('reporte_informe_revisor_xls',view.ReporteInformeRevisorXlsView,name='reporte_informe_revisor_xls'),
    path('reportes_informe_revisor_pdf/',view.ReportesInformeRevisorPdfView.as_view(),name='reportes_informe_revisor_pdf'),
    path('reporte_informe_revisor_pdf/<int:tipo>/',view.ReporteInformeRevisorPdfView,name='reporte_informe_revisor_pdf'),
    path('paginas_informe_revisor_pdf/<int:pagina>/<int:tipo>/',view.PaginasReporteInformeRevisorPdfView,name='paginas_informe_revisor_pdf'),
    path('ajax_guarda_id_informe',view.AjaxGuardaIdInformeView,name='ajax_guarda_id_informe'),

    path('lista_asambleas',view.ListaAsambleaView,name='lista_asambleas'),
    path('crea_asamblea/',view.CreaAsambleaView.as_view(),name='crea_asamblea'),
    path('edita_asamblea/<int:pk>/',view.EditaAsambleaView.as_view(),name='edita_asamblea'),
    path('borra_asamblea/<int:pk>/',view.BorraAsambleaView.as_view(),name='borra_asamblea'),
    path('detalle_asamblea/<int:id>/',view.DetalleAsambleaView,name='detalle_asamblea'),
    path('reporte_asamblea_xls/',view.ReporteAsambleasXlsView,name='reporte_asamblea_xls'),
    path('tipo_reporte_asambleas_pdf/',view.TipoReportesAsambleasPdfView.as_view(),name='tipo_reporte_asambleas_pdf'),
    path('reporte_asambleas_pdf/<int:tipo>',view.ReporteAsambleasPdfView,name='reporte_asambleas_pdf'),
    path('paginas_reporte_asambleas_pdf/<int:pagina>/<int:tipo>',view.PaginasReporteAsambleasPdfView,name='paginas_reporte_asambleas_pdf'),
    path('guarda_fecha_asamblea',view.GuardaFechaAsambleaView,name=''),
    path('asamblea_contenido/<int:id>/',view.AsambleaContenidoView,name='asamblea_contenido'),
    path('ajax_guarda_id_asamblea',view.AjaxGuardaIdReunionView,name='ajax_guarda_id_asamblea'),
    path('crea_decision_asamblea/<int:id>/',view.CreaDecisionAsambleaView.as_view(),name='crea_decision_asamblea'),
    path('edita_decision_asamblea/<int:pk>/',view.EditaDecisionAsambleaView.as_view(),name='edita_decision_asamblea'),
    path('borra_decision_asamblea/<int:pk>/',view.BorraDecisionAsambleaView.as_view(),name='borra_decision_asamblea'),
    path('borra_anexo_asamblea/<int:pk>/',view.BorraAnexoAsambleaView.as_view(),name='borra_anexo_asamblea'),
    path('publicar_asamblea/<int:id>/',view.PublicaAsambleaView,name='publicar_asamblea'),


    path('crea_recomendacion_revisor/<int:id>/',view.CreaRecomendacionView.as_view(),name='crea_recomendacion_revisor'),
    path('borra_recomendacion_revisor/<int:pk>/',view.BorraRecomendacionView.as_view(),name='borra_recomendacion_revisor'),
    path('edita_recomendacion_revisor/<int:pk>/',view.EditaRecomendacionView.as_view(),name='edita_recomendacion_revisor'),
    path('aplica_recomendacion_revisor/<int:pk>/',view.AplicaRecomendacionView.as_view(),name='aplica_recomendacion_revisor'),

    path('lista_procesos_juridicos',view.ListaProcesosJuridicosView,name='lista_procesos_juridicos'),
    path('proceso_juridico_detalle/<int:id>/',view.ProcesoJuridicoDetalleView,name='proceso_juridico_detalle'),
    path('crea_proceso_juridico',view.CreaProcesoJuridicoView.as_view(),name='crea_proceso_juridico'),
    path('edita_proceso_juridico/<int:pk>/',view.EditaProcesoJuridicoView.as_view(),name='edita_proceso_juridico'),
    path('borra_proceso_juridico/<int:pk>/',view.BorraProcesoJuridicoView.as_view(),name='borra_proceso_juridico'),
    path('imprimir_proceso_juridico/<int:id>/',view.MensajePaginaEnConstruccionView,name='imprimir_proceso_juridico'),
    path('publicar_proceso_juridico/<int:id>/',view.MensajePaginaEnConstruccionView,name='publicar_proceso_juridico'),
    path('borra_anexo_proceso_juridico/<int:pk>/',view.BorraAnexoProcesoJuridicoView.as_view(),name='borra_anexo_proceso_juridico'),
    path('crea_tipo_proceso/',view.CreaTipoProcesoView.as_view(),name='crea_tipo_proceso'),
    path('guarda_numero_proceso/',view.GuardaNumeroProcesoView,name='guarda_numero_proceso'),
    path('cargar_numero_proceso/',view.CargarNumeroProcesoView,name='cargar_numero_proceso'),
    path('reporte_procesos_xls',view.ReporteProcesosJuridicosXlsView,name='reporte_procesos_xls'),
    path('reporte_procesos_pdf',view.ReporteProcesosJuridicosPdfView,name='reporte_procesos_pdf'),
    path('paginas_procesos_juridicos_pdf/<int:pagina>',view.PaginasReporteProcesosJuridicosPdfView,name='paginas_procesos_juridicos_pdf'),
    path('crea_gestion_proceso_juridico/<int:id>/',view.CreaGestionProcesoJuridicoView.as_view(),name='crea_gestion_proceso_juridico'),
    path('edita_gestion_proceso_juridico/<int:pk>/',view.EditaGestionProcesoJuridicoView.as_view(),name='edita_gestion_proceso_juridico'),
    path('borra_gestion_procesojuridico/<int:pk>/',view.BorraGestionProcesoJuridicoView.as_view(),name='borra_gestion_proceso_juridico'),
    path('borra_anexo_proceso_juridico/<int:pk>/',views.BorraAnexoProcesoJuridicoView.as_view(),name='borra_anexo_proceso_juridico'),
    path('borra_anexo_gestion_proceso_juridico/<int:pk>/',views.BorraAnexoGestionProcesoJuridicoView.as_view(),name='borra_anexo_gestion_proceso_juridico'),    
    path('proceso_juridico_contenido/<int:id>/',view.ProcesoJuridicoContenidoView,name='proceso_juridico_contenido'),
    path('reporte_gestion_proceso_pdf/<int:id>/',view.ReporteGestionProcesoPdfView,name='reporte_gestion_proceso_pdf'),
    path('paginas_gestion_proceso_pdf/<int:pagina>',view.PaginasGestionProcesoPdfView,name='paginas_gestion_proceso_pdf'),
    path('direcciona_salidad_procesos_juridicos',view.DireccionaSalidaProcesosJuridicosView,name='direcciona_salidad_procesos_juridicos'),
    path('ajax_guarda_id_proceso',view.AjaxGuardaIdProcesoView,name='ajax_guarda_id_proceso'),

    #path('pagina_staff/',view.PaginaStaffView.as_view(), name="pagina_staff"),
    path('lista_miembros_staff/',view.ListaMiembrosStaffView,name='lista_miembros_staff'),
    path('crea_miembro_staff/',view.CreaMiembroStaffView.as_view(),name='crea_miembro_staff'),
    path('edita_miembro_staff/<int:pk>/',view.EditaMiembroStaffView.as_view(),name='edita_miembro_staff'),
    path('borra_miembro_staff/<int:pk>/',view.BorraMiembroStaffView.as_view(),name='borra_miembro_staff'),
    path('carga_foto_miembro_staff/<int:id>',view.CargaFotoMiembroStaffView,name='carga_foto_miembro_staff'),
    path('ajax_switch_envio_staff/',view.ajaxSwitchEnvioStaffView,name='ajax_switch_envio_staff'),
    path('ajax_switch_comunidad_staff/',view.ajaxSwitchComunidadStaffView,name='ajax_switch_comunidad_staff'),
    path('ajax_switch_publicar_staff/',view.ajaxSwitchPublicarStaffView,name='ajax_switch_publicar_staff'),

    path('lista_vigilantes/',view.ListaVigilantesView,name='lista_vigilantes'),
    path('crea_vigilante/',view.CreaVigilanteView.as_view(),name='crea_vigilante'),
    path('edita_vigilante/<int:pk>/',view.EditaVigilanteView.as_view(),name='edita_vigilante'),
    path('borra_vigilante/<int:pk>/',view.BorraVigilanteView.as_view(),name='borra_vigilante'),

    #path('tomar_foto',view.tomar_foto, name="tomar_foto"),
    #path('save_image',view.save_image, name="save_image"),
    #path('scan-upload',view.scan_and_upload,name='scan-upload')

    path('contactenos',view.ContactView,name='contactenos'),

    ] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
