# Generated by Django 2.1.7 on 2019-05-21 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingreso_peatonal',
            options={'ordering': ['hora_ingreso'], 'verbose_name': 'Ingreso Peatonal', 'verbose_name_plural': 'Ingresos Peatonales'},
        ),
    ]
