# Generated by Django 2.2.4 on 2019-08-13 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingreso_peatonal',
            options={'ordering': ['hora_ingreso'], 'verbose_name': 'Ingreso Peatonal', 'verbose_name_plural': 'Ingresos Peatonales'},
        ),
        migrations.RemoveField(
            model_name='ingreso_peatonal',
            name='foto',
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='clase_correspondencia',
            field=models.CharField(choices=[('sobre', 'Sobre'), ('paquete', 'Paquete')], default='', max_length=10, verbose_name='Clase de Correspondencia'),
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='detalle',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Detalle'),
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='entregado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='correspondencia',
            name='fecha_recibo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='correspondencia',
            name='tipo_correspondencia',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgente', 'Urgente')], default='', max_length=10, verbose_name='Tipo de Correspondencia'),
        ),
        migrations.AlterField(
            model_name='correspondencia',
            name='vigilante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Vigilante'),
        ),
        migrations.AlterField(
            model_name='ingreso_peatonal',
            name='apartamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Apartamento', verbose_name='Apartamento'),
        ),
        migrations.AlterField(
            model_name='ingreso_peatonal',
            name='hora_salida',
            field=models.DateTimeField(auto_now=True, verbose_name='Hora de Salida'),
        ),
        migrations.AlterField(
            model_name='ingreso_peatonal',
            name='identificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Visitante', verbose_name='Identificaciòn'),
        ),
        migrations.AlterField(
            model_name='ingreso_peatonal',
            name='interior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Interior', verbose_name='Interior'),
        ),
        migrations.AlterField(
            model_name='ingreso_peatonal',
            name='tipoingreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TipoIngreso', verbose_name='Tipo de Ingreso'),
        ),
        migrations.AlterField(
            model_name='ingreso_peatonal',
            name='vigilante',
            field=models.CharField(max_length=15, verbose_name='Vigilante'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='foto',
            field=models.ImageField(blank=True, default='/static/img/no-avatar.jpg', null=True, upload_to='static/'),
        ),
    ]
