# Generated by Django 2.1.7 on 2019-05-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190521_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingreso_peatonal',
            name='foto',
        ),
        migrations.AlterField(
            model_name='visitante',
            name='foto',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
