# Generated by Django 2.1.4 on 2019-07-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190521_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso_peatonal',
            name='vigilante',
            field=models.CharField(max_length=15, verbose_name='Vigilante'),
        ),
    ]
