# Generated by Django 2.2.4 on 2019-08-29 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190820_1220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
