# Generated by Django 2.1.7 on 2019-07-30 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190718_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondencia',
            name='Detalle',
            field=models.CharField(default='', max_length=300, verbose_name='Detalle'),
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='clase_correspondencia',
            field=models.CharField(choices=[('general', 'General'), ('personal', 'Personal')], default='', max_length=10, verbose_name='Clase de Correspondencia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingreso_peatonal',
            name='identificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Visitante', verbose_name='Visitante'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='foto',
            field=models.ImageField(blank=True, default='/static/img/no-avatar.jpg', null=True, upload_to='static/'),
        ),
    ]
