# Generated by Django 2.2.4 on 2019-08-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190730_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencia',
            name='Detalle',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Detalle'),
        ),
        migrations.AlterField(
            model_name='correspondencia',
            name='tipo_correspondencia',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgente', 'Urgente')], default='', max_length=10, verbose_name='Tipo de Correspondencia'),
        ),
    ]
