# Generated by Django 2.2.4 on 2019-08-10 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_helloworldprocess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencia',
            name='vigilante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Vigilante'),
        ),
        migrations.AlterField(
            model_name='ingreso_peatonal',
            name='apartamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Apartamento', verbose_name='Apartamento'),
        ),
        migrations.AlterField(
            model_name='ingreso_peatonal',
            name='hora_salida',
            field=models.DateTimeField(auto_now=True, verbose_name='Hora de Salida'),
        ),
        migrations.AlterField(
            model_name='ingreso_peatonal',
            name='identificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Visitante', verbose_name='Identificaciòn'),
        ),
        migrations.AlterField(
            model_name='ingreso_peatonal',
            name='interior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Interior', verbose_name='Interior'),
        ),
        migrations.AlterField(
            model_name='ingreso_peatonal',
            name='tipoingreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TipoIngreso', verbose_name='Tipo de Ingreso'),
        ),
    ]
