# Generated by Django 3.1.13 on 2023-03-27 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAnexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AnexoReunionConsejo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='', max_length=50)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='upload/anexos')),
                ('publicar', models.BooleanField(default=False, verbose_name='Publicar Anexo ')),
                ('reunion', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anexo_reunion', to='core.reunionconsejo', verbose_name='Reunión Consejo')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoReparacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='', max_length=50)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='upload/anexos')),
                ('reparacion', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anexo_reparacion', to='core.reparacion', verbose_name='Reparación')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='', max_length=50)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='upload/anexos')),
                ('publicar', models.BooleanField(default=False, verbose_name='Publicar Anexo ')),
                ('proyecto', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anexo_proyecto_proponente', to='core.proyecto', verbose_name='Anexo Proyecto Proponente')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoProveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='', max_length=50)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='upload/anexos')),
                ('publicar', models.BooleanField(default=False, verbose_name='Publicar Anexo ')),
                ('proveedor', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anexo_proveedor', to='core.proveedor', verbose_name='Anexo Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoProponenteProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='', max_length=50)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='upload/anexos')),
                ('publicar', models.BooleanField(default=False, verbose_name='Publicar Anexo ')),
                ('proponente_proyecto', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proponente_proyecto', to='core.proponenteproyecto', verbose_name='Proponente Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoProponente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='', max_length=50)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='upload/anexos')),
                ('publicar', models.BooleanField(default=False, verbose_name='Publicar Anexo ')),
                ('proponente', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anexo_proponente', to='core.proponente', verbose_name='Anexo Proponente')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoProcesoJuridico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='', max_length=50)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='upload/anexos')),
                ('publicar', models.BooleanField(default=False, verbose_name='Publicar Anexo ')),
                ('proceso_juridico', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anexo_proceso_juridico', to='core.procesojuridico', verbose_name='Anexo Proceso Juridico')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoObra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='', max_length=50)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='upload/anexos')),
                ('obra', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anexo_obra', to='core.obra', verbose_name='Obra')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoNormatividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='', max_length=50)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='upload/anexos')),
                ('publicar', models.BooleanField(default=False, verbose_name='Publicar Anexo ')),
                ('normatividad', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anexo_normatividad', to='pages.normatividad', verbose_name='Anexo Normatividad')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoMantenimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='', max_length=50)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='upload/anexos')),
                ('mantenimiento', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anexo_mantenimiento', to='core.mantenimiento', verbose_name='Mantenimiento')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoLegislacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='', max_length=50)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='upload/anexos')),
                ('publicar', models.BooleanField(default=False, verbose_name='Publicar Anexo ')),
                ('legislacion', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anexo_legislacion', to='pages.legislacion', verbose_name='Anexo Legislación')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoInformeRevisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='', max_length=50)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='upload/anexos')),
                ('publicar', models.BooleanField(default=False, verbose_name='Publicar Anexo ')),
                ('informe_revisor', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anexo_informe_revisor', to='core.InformeRevisor', verbose_name='Anexo Informe Auditor')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoGestionProcesoJuridico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='', max_length=50)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='upload/anexos')),
                ('publicar', models.BooleanField(default=False, verbose_name='Publicar Anexo ')),
                ('gestion_proceso_juridico', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anexo_gestion_proceso_juridico', to='core.gestionprocesojuridico', verbose_name='Anexo Gestion Proceso Juridico')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='', max_length=50)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='upload/anexos')),
                ('contrato', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anexo_contrato', to='core.contrato', verbose_name='Contrato No.')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoComunicado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='', max_length=50)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='upload/anexos')),
                ('publicar', models.BooleanField(default=False, verbose_name='Publicar Anexo ')),
                ('comunicado', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anexo_legislacion', to='pages.comunicado', verbose_name='Anexo Legislación')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoBajaActivoFijo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='', max_length=50)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='upload/anexos')),
                ('publicar', models.BooleanField(default=False, verbose_name='Publicar Anexo ')),
                ('activo_fijo', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anexo_baja_activo_fijo', to='core.activofijo', verbose_name='Anexo BajaActivoFijo')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoAvanceObra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='', max_length=50)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='upload/anexos')),
                ('avance_obra', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anexo_avance_obra', to='core.avanceobra', verbose_name='Avance Obra')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoAsamblea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='', max_length=50)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='upload/anexos')),
                ('publicar', models.BooleanField(default=False, verbose_name='Publicar Anexo ')),
                ('asamblea', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anexo_asamblea', to='core.asamblea', verbose_name='Anexo Asamblea')),
            ],
        ),
    ]
