# Generated by Django 3.1.13 on 2023-03-28 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20230328_1615'),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anexobajaactivofijo',
            name='activo_fijo',
        ),
        migrations.AddField(
            model_name='anexobajaactivofijo',
            name='baja_activo',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anexo_baja_activo_fijo', to='core.bajaactivofijo', verbose_name='Anexo BajaActivoFijo'),
        ),
    ]
