# Generated by Django 3.1.13 on 2022-10-25 21:09

import datetime
from django.db import migrations, models
import ckeditor.fields
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20221025_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(16, 9, 38, 233418), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(16, 9, 38, 233418), verbose_name='Hora Inicio'),
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.DateTimeField(default=None, help_text='Ingrese la Hora de Inicio')),
                ('hora_final', models.DateTimeField(default=None, help_text='Ingrese la Hora Final')),
                ('estado', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zona_comun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.zonacomun')),
            ],
            options={
                'verbose_name': 'Reserva Zona Común',
                'verbose_name_plural': 'Reservas Zonas Comunes',
                'ordering': ['zona_comun'],
            },
        ),
    ]
