# Generated by Django 3.1.13 on 2022-10-26 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20221025_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComiteConvivencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=60, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('envio', models.BooleanField(choices=[('SI', 'Si'), ('NO', 'No')], default='False', max_length=2, verbose_name='Envío Cominicado')),
                ('foto', models.ImageField(blank=True, default='/static/img/no-avatar.jpg', null=True, upload_to='static/')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('publicar', models.BooleanField(default=False, verbose_name='Publicar en Web')),
                ('comunidad', models.BooleanField(default=False, verbose_name='Publicar sólo a Cominidad')),
            ],
            options={
                'verbose_name': 'Miembro Comite Convivencia',
                'verbose_name_plural': 'Miembros Comite Convivencia',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='miembrostaff',
            options={'ordering': ['nombre'], 'verbose_name': 'Miembro Staff', 'verbose_name_plural': 'Miembros Staff'},
        ),
        migrations.AddField(
            model_name='miembroconsejo',
            name='comunidad',
            field=models.BooleanField(default=False, verbose_name='Publicar sólo a Cominidad'),
        ),
        migrations.AddField(
            model_name='miembroconsejo',
            name='publicar',
            field=models.BooleanField(default=False, verbose_name='Publicar en Web'),
        ),
        migrations.AddField(
            model_name='miembrostaff',
            name='comunidad',
            field=models.BooleanField(default=False, verbose_name='Publicar sólo a Cominidad'),
        ),
        migrations.AddField(
            model_name='miembrostaff',
            name='publicar',
            field=models.BooleanField(default=False, verbose_name='Publicar en Web'),
        ),
        migrations.AlterField(
            model_name='comiteconviviencia',
            name='envio',
            field=models.BooleanField(default=False, max_length=2, verbose_name='Envío Cominicado'),
        ),
        migrations.AlterField(
            model_name='miembrostaff',
            name='envio',
            field=models.BooleanField(default='False', max_length=2, verbose_name='Envío Cominicado'),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='Pagado'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(9, 59, 54, 617503), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(9, 59, 54, 617503), verbose_name='Hora Inicio'),
        ),
    ]
