# Generated by Django 3.1.13 on 2022-10-27 21:01

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20221027_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Proyecto',
                'verbose_name_plural': 'Tipos de Proyectos',
                'ordering': ['descripcion'],
            },
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='terminado',
            field=models.BooleanField(blank=True, default=False, max_length=2, verbose_name='Terminado'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(16, 1, 5, 963497), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(16, 1, 5, 963497), verbose_name='Hora Inicio'),
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, default=None, null=True, verbose_name='Fecha')),
                ('descripcion', models.TextField(blank=True, default='', null=True, verbose_name='Descripción')),
                ('aprobado', models.BooleanField(blank=True, default=False, max_length=2, verbose_name='Aprobado')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha Aprobación')),
                ('presupuesto', models.FloatField(default=0, verbose_name='Valor Presupuesto')),
                ('calificacion', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Calificación')),
                ('tipo_proyecto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.tipoproyecto')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProponenteProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, default=None, null=True, verbose_name='Fecha')),
                ('descripcion', models.TextField(blank=True, default='', null=True, verbose_name='Descripción')),
                ('valor', models.FloatField(default=0, verbose_name='Valor Propuesta')),
                ('seleccionado', models.BooleanField(blank=True, default=False, max_length=2, verbose_name='Seleccionado')),
                ('fecha_aprobacion', models.DateField(blank=True, default=None, null=True, verbose_name='Fecha Aprobación')),
                ('votos_favor', models.IntegerField(default=0, verbose_name='Votaciones a Favor')),
                ('votos_contra', models.IntegerField(default=0, verbose_name='Votaciones en Contra')),
                ('proponente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proponente_proyecto', to='core.proponente')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proponente_proyecto', to='core.proyecto')),
            ],
            options={
                'verbose_name': 'Proponente Proyecto',
                'verbose_name_plural': 'Proponente Proyecto',
                'ordering': ['id'],
            },
        ),
    ]
