# Generated by Django 3.1.13 on 2022-10-27 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20221027_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='calificacion',
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(17, 11, 3, 944103), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(17, 11, 3, 944103), verbose_name='Hora Inicio'),
        ),
    ]
