# Generated by Django 3.1.13 on 2022-10-28 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20221027_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='aprobado',
            field=models.BooleanField(default=False, verbose_name='Aprobado'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(12, 32, 48, 804225), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(12, 32, 48, 804225), verbose_name='Hora Inicio'),
        ),
    ]
