# Generated by Django 3.1.13 on 2022-10-28 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20221028_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='aprobado_por',
            field=models.CharField(blank=True, choices=[('No Determinado', 'No Determinado'), ('Asamblea', 'Asamblea'), ('Consejo', 'Consejo'), ('Administrador', 'Administrador')], default='No Determinado', max_length=15, null=True, verbose_name='Aprobado Por'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(12, 46, 22, 442529), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(12, 46, 22, 442529), verbose_name='Hora Inicio'),
        ),
    ]
