# Generated by Django 3.1.13 on 2022-11-01 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20221101_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proponente',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='proponente',
            name='telefono_contacto',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Teléfono Contacto'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(16, 22, 51, 447501), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(16, 22, 51, 447501), verbose_name='Hora Inicio'),
        ),
    ]
