# Generated by Django 3.1.13 on 2022-11-02 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20221101_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proponente',
            name='celular',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='proponente',
            name='celular_contacto',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Celular Contacto'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='celular',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='celular_contacto',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Celular Contacto'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(default='', max_length=80, verbose_name='Nombre/Razón Social'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono_contacto',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Teléfono Contacto'),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='terminado',
            field=models.BooleanField(blank=True, default=False, verbose_name='Terminado'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(15, 2, 32, 823869), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(15, 2, 32, 823869), verbose_name='Hora Inicio'),
        ),
    ]
