# Generated by Django 3.1.13 on 2022-11-10 22:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20221102_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proponente',
            name='servicio_provee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicioproveedor', verbose_name='Servicio Proponente'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(17, 25, 50, 787813), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(17, 25, 50, 787813), verbose_name='Hora Inicio'),
        ),
    ]
