# Generated by Django 3.1.13 on 2022-11-18 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20221116_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='vigilante',
            name='comunidad',
            field=models.BooleanField(default=False, verbose_name='Publicar sólo a Cominidad'),
        ),
        migrations.AddField(
            model_name='vigilante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
        migrations.AddField(
            model_name='vigilante',
            name='orden',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='vigilante',
            name='publicar',
            field=models.BooleanField(default=False, verbose_name='Publicar en Web'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(12, 16, 14, 778930), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(12, 16, 14, 778930), verbose_name='Hora Inicio'),
        ),
    ]
