# Generated by Django 3.1.13 on 2022-11-19 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20221118_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='conjunto',
            name='horario_administrador',
            field=models.TextField(default='', verbose_name='Horario Adminsitrador'),
        ),
        migrations.AlterField(
            model_name='conjunto',
            name='razon_social',
            field=models.CharField(default='', max_length=100, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='conjunto',
            name='telefono',
            field=models.CharField(default='', max_length=30, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(17, 28, 10, 57792), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(17, 28, 10, 56788), verbose_name='Hora Inicio'),
        ),
    ]
