# Generated by Django 3.1.13 on 2022-12-09 01:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20221119_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizado',
            name='dias',
            field=models.IntegerField(default=0, verbose_name='Dias'),
        ),
        migrations.AddField(
            model_name='autorizado',
            name='permanente',
            field=models.BooleanField(default=False, verbose_name='Permanente'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(20, 12, 17, 905), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(20, 12, 17, 905), verbose_name='Hora Inicio'),
        ),
    ]
