# Generated by Django 3.1.13 on 2022-12-09 02:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20221208_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresopeatonal',
            name='nombre',
            field=models.CharField(default='', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(21, 31, 19, 912910), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(21, 31, 19, 912910), verbose_name='Hora Inicio'),
        ),
    ]
