# Generated by Django 3.1.13 on 2022-12-12 23:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20221208_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='terminado',
        ),
        migrations.AddField(
            model_name='obra',
            name='terminada',
            field=models.BooleanField(default=False, verbose_name='Terminada'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='terminado',
            field=models.BooleanField(default=False, verbose_name='Terminado'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(18, 27, 10, 279928), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(18, 27, 10, 279928), verbose_name='Hora Inicio'),
        ),
    ]
