# Generated by Django 3.1.13 on 2022-12-15 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20221215_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='saldo_pagar',
            field=models.FloatField(default=0, verbose_name='Saldo Por Pagar'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(11, 34, 33, 244523), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(11, 34, 33, 244523), verbose_name='Hora Inicio'),
        ),
    ]
