# Generated by Django 3.1.13 on 2023-01-10 21:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20221215_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(16, 48, 24, 581269), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(16, 48, 24, 581269), verbose_name='Hora Inicio'),
        ),
        migrations.CreateModel(
            name='PrestamoActivoFijo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, default=None, null=True, verbose_name='Fecha')),
                ('responsable', models.TextField(blank=True, default='', null=True, verbose_name='Responsable')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('devuelto', models.BooleanField(default=False, verbose_name='Terminado')),
                ('activo_fijo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activo_prestamo', to='core.activofijo')),
            ],
            options={
                'verbose_name': 'Préstamo Activo Fijo',
                'verbose_name_plural': 'Préstamos Activos Fijos',
                'ordering': ['id'],
            },
        ),
    ]
