# Generated by Django 3.1.13 on 2023-01-10 23:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20230110_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='activofijo',
            name='prestado',
            field=models.BooleanField(default=False, verbose_name='En Préstamo'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(18, 34, 42, 735121), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(18, 34, 42, 735121), verbose_name='Hora Inicio'),
        ),
    ]
