# Generated by Django 3.1.13 on 2023-01-14 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20230110_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamoactivofijo',
            name='devuelto',
            field=models.BooleanField(default=False, verbose_name='Devuelto'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(16, 53, 9, 654815), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(16, 53, 9, 654815), verbose_name='Hora Inicio'),
        ),
    ]
