# Generated by Django 3.1.13 on 2023-01-19 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20230114_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamoactivofijo',
            name='dias',
            field=models.IntegerField(default=0, verbose_name='Dias'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(13, 2, 35, 982537), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(13, 2, 35, 982537), verbose_name='Hora Inicio'),
        ),
    ]
