# Generated by Django 3.1.13 on 2023-01-19 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20230119_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamoactivofijo',
            name='dias',
            field=models.TimeField(default='', verbose_name='Dias'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(13, 8, 0, 271159), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(13, 8, 0, 270160), verbose_name='Hora Inicio'),
        ),
    ]
