# Generated by Django 3.1.13 on 2023-01-19 22:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20230119_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamoactivofijo',
            name='dias',
            field=models.CharField(default='', max_length=20, verbose_name='Dias'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(17, 19, 8, 940860), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(17, 19, 8, 940860), verbose_name='Hora Inicio'),
        ),
    ]
