# Generated by Django 3.1.13 on 2023-02-07 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20230119_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autorizado',
            name='dias',
        ),
        migrations.AddField(
            model_name='autorizado',
            name='fecha_final',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Fecha Final'),
        ),
        migrations.AddField(
            model_name='autorizado',
            name='fecha_inicial',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Fecha Inicial'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(9, 17, 56, 999481), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(9, 17, 56, 999481), verbose_name='Hora Inicio'),
        ),
    ]
