# Generated by Django 3.1.13 on 2023-02-23 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20230207_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestionprocesojuridico',
            name='titulo',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(17, 1, 7, 81133), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(17, 1, 7, 81133), verbose_name='Hora Inicio'),
        ),
    ]
