# Generated by Django 3.1.13 on 2023-02-28 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20230223_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reunionconsejo',
            name='contenido',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(10, 29, 33, 495253), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(10, 29, 33, 495253), verbose_name='Hora Inicio'),
        ),
    ]
