# Generated by Django 3.1.13 on 2023-02-28 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20230228_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_final',
            field=models.DateTimeField(blank=True, default=datetime.time(17, 40, 18, 232549), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_inicio',
            field=models.DateTimeField(blank=True, default=datetime.time(17, 40, 18, 232549), verbose_name='Hora Inicio'),
        ),
    ]
