# Generated by Django 3.1.13 on 2023-03-06 17:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20230302_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesojuridico',
            name='abogado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedor_abogado', to='core.proveedor', verbose_name='Abogado'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(12, 16, 22, 558087), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(12, 16, 22, 558087), verbose_name='Hora Inicio'),
        ),
    ]
