# Generated by Django 3.1.13 on 2023-03-06 17:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20230306_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesojuridico',
            name='abogado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abogado_proveedor', to='core.proveedor', verbose_name='Abogado'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(12, 17, 59, 750741), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(12, 17, 59, 750741), verbose_name='Hora Inicio'),
        ),
    ]
