# Generated by Django 3.1.13 on 2023-03-06 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20230306_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='InformeRevisor',
            name='contenido',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(17, 5, 23, 862177), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(17, 5, 23, 862177), verbose_name='Hora Inicio'),
        ),
    ]
