# Generated by Django 3.1.13 on 2023-03-09 21:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20230308_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='asamblea',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(16, 19, 22, 971100), verbose_name='Hora Final'),
        ),
        migrations.AddField(
            model_name='asamblea',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(16, 19, 22, 971100), verbose_name='Hora Inicio'),
        ),
        migrations.AddField(
            model_name='asamblea',
            name='numero_acta',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Número Acta'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(16, 19, 22, 965119), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(16, 19, 22, 965119), verbose_name='Hora Inicio'),
        ),
        migrations.CreateModel(
            name='DecisionAsamblea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(blank=True, default='', max_length=250, verbose_name='Decisión')),
                ('numero_votos_contra', models.IntegerField(default=0, verbose_name='Número de Votos Contra')),
                ('numero_votos_favor', models.IntegerField(default=0, verbose_name='Número de Votos Favor')),
                ('asamblea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asamblea_decision', to='core.asamblea')),
            ],
            options={
                'verbose_name': 'Decisión Asamblea',
                'verbose_name_plural': 'Decisiones Asamblea',
                'ordering': ['id'],
            },
        ),
    ]
