# Generated by Django 3.1.13 on 2023-03-17 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20230310_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='fecha',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='asamblea',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(11, 34, 36, 978592), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='asamblea',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(11, 34, 36, 978592), verbose_name='Hora Inicio'),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='hora_final',
            field=models.TimeField(default=None, help_text='Ingrese la Hora Final'),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='hora_inicio',
            field=models.TimeField(default=None, help_text='Ingrese la Hora de Inicio'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(11, 34, 36, 969593), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(11, 34, 36, 969593), verbose_name='Hora Inicio'),
        ),
    ]
