# Generated by Django 3.1.13 on 2023-03-24 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20230324_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asamblea',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(17, 29, 44, 849407), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='asamblea',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(17, 29, 44, 849407), verbose_name='Hora Inicio'),
        ),
        migrations.AlterField(
            model_name='miembrostaff',
            name='cargo',
            field=models.CharField(choices=[('*', 'No determinado'), ('R', 'Revisor Fiscal'), ('C', 'Contador')], default='*', max_length=1, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(17, 29, 44, 840406), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(17, 29, 44, 840406), verbose_name='Hora Inicio'),
        ),
    ]
