# Generated by Django 3.1.13 on 2023-03-24 22:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20230324_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asamblea',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(17, 30, 30, 644156), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='asamblea',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(17, 30, 30, 644156), verbose_name='Hora Inicio'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(17, 30, 30, 638156), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(17, 30, 30, 638156), verbose_name='Hora Inicio'),
        ),
        migrations.CreateModel(
            name='ComiteConvivencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=60, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('envio', models.BooleanField(default=False, max_length=2, verbose_name='Envío Cominicado')),
                ('activo', models.BooleanField(default='False', max_length=2, verbose_name='Miembro Activo')),
                ('publicar', models.BooleanField(default=False, verbose_name='Publicar en Web')),
                ('comunidad', models.BooleanField(default=False, verbose_name='Publicar sólo a Cominidad')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('foto', models.ImageField(blank=True, default='/static/img/no-avatar.jpg', null=True, upload_to='static/')),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.apartamento', verbose_name='Apartamento')),
                ('interior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.interior', verbose_name='Interior')),
            ],
            options={
                'verbose_name': 'Comité Convivencia',
                'verbose_name_plural': 'Comité Convivencia',
                'ordering': ['id'],
            },
        ),
    ]
