# Generated by Django 3.1.13 on 2023-03-27 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230327_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='activofijo',
            name='estado',
            field=models.CharField(blank=True, choices=[('Activo', 'Activo'), ('Baja', 'Baja')], default='Activo', max_length=10, verbose_name='eSTADO'),
        ),
        migrations.AlterField(
            model_name='asamblea',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(9, 29, 51, 647637), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='asamblea',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(9, 29, 51, 647637), verbose_name='Hora Inicio'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(9, 29, 51, 641638), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(9, 29, 51, 641638), verbose_name='Hora Inicio'),
        ),
    ]
