# Generated by Django 3.1.13 on 2023-03-27 16:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230327_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asamblea',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(11, 54, 16, 268430), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='asamblea',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(11, 54, 16, 268430), verbose_name='Hora Inicio'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(11, 54, 16, 261437), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(11, 54, 16, 261437), verbose_name='Hora Inicio'),
        ),
        migrations.CreateModel(
            name='BajaActivoFijo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, default=None, null=True, verbose_name='Fecha')),
                ('detalle', models.TextField(blank=True, default='', null=True, verbose_name='Responsable')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('causa_baja', models.CharField(blank=True, choices=[('Obsolescencia', 'Obsolescencia'), ('Desperfecto', 'Desperfecto'), ('Mal Estado', 'Mal Estado')], default='NO', max_length=15, verbose_name='Causa Baja')),
                ('activo_fijo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activo_baja', to='core.activofijo')),
            ],
            options={
                'verbose_name': 'Baja Activo Fijo',
                'verbose_name_plural': 'Bajas Activos Fijos',
                'ordering': ['fecha'],
            },
        ),
    ]
