# Generated by Django 3.1.13 on 2023-03-28 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230328_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asamblea',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(16, 15, 24, 149355), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='asamblea',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(16, 15, 24, 149355), verbose_name='Hora Inicio'),
        ),
        migrations.AlterField(
            model_name='bajaactivofijo',
            name='detalle',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Detalle'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(16, 15, 24, 142355), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(16, 15, 24, 142355), verbose_name='Hora Inicio'),
        ),
    ]
