# Generated by Django 3.1.13 on 2023-03-31 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20230331_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='anexo_pago',
            field=models.BooleanField(default=False, verbose_name='Anexo Pago'),
        ),
        migrations.AlterField(
            model_name='asamblea',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(13, 5, 53, 225705), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='asamblea',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(13, 5, 53, 225705), verbose_name='Hora Inicio'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(13, 5, 53, 219703), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(13, 5, 53, 219703), verbose_name='Hora Inicio'),
        ),
    ]
