# Generated by Django 3.1.13 on 2023-03-31 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20230331_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='confirmada',
            field=models.BooleanField(default=False, verbose_name='Confirmada'),
        ),
        migrations.AlterField(
            model_name='asamblea',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(18, 1, 9, 555135), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='asamblea',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(18, 1, 9, 555135), verbose_name='Hora Inicio'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(18, 1, 9, 549131), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(18, 1, 9, 549131), verbose_name='Hora Inicio'),
        ),
    ]
