# Generated by Django 3.1.13 on 2023-05-03 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20230428_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informerevisor',
            options={'ordering': ['id'], 'verbose_name': 'Informe Revisor', 'verbose_name_plural': 'Informes Revisor'},
        ),
        migrations.AlterField(
            model_name='asamblea',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(11, 31, 50, 443994), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='asamblea',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(11, 31, 50, 443994), verbose_name='Hora Inicio'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(11, 31, 50, 438996), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(11, 31, 50, 438996), verbose_name='Hora Inicio'),
        ),
    ]
