# Generated by Django 4.0.6 on 2023-09-18 21:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20230503_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamoactivofijo',
            name='fecha_devuelto',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Fecha Devuelto'),
        ),
        migrations.AlterField(
            model_name='asamblea',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(16, 46, 25, 245347), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='asamblea',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(16, 46, 25, 245347), verbose_name='Hora Inicio'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_final',
            field=models.TimeField(blank=True, default=datetime.time(16, 46, 25, 237347), verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='reunionconsejo',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(16, 46, 25, 237347), verbose_name='Hora Inicio'),
        ),
    ]
