# Generated by Django 3.1.13 on 2023-04-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqr',
            name='pendiente',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Pendiente'),
        ),
    ]
